### ISSUE TITLE
Handle errros from pinata

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/nft.storage#102]
At the moment failure to pin on pinata just logs an error in console

https://github.com/ipfs-shipyard/nft.storage/blob/35fe3adcab4e27e7c4402fd89c4308c04522dcdd/site/src/routes/nfts-upload.js#L79-L88

As it turns out `pinByHash` was failing all along because `Content-Type` header was missing, but we missed it because those errors were handled or reported.

**Comment by alanshaw** [comment]
This is resolved in #100 - errors are captured and reported to Sentry.

**Comment by Gozala** [comment]
And #56 fixes the mentioned issue
