### ISSUE TITLE
CORS / Access-Control-Allow-Origin using storeBlob

### ISSUE THREAD

**Issue by glitch003** [ipfs-shipyard/nft.storage#134]
I am unable to upload from the browser using the storeBlob method because of the error that no Access-Control-Allow-Origin header is present.  Could you add Access-Control-Allow-Origin: * to the API?

Thanks!

**Comment by alanshaw** [comment]
Sorry for the delay - are you still having this problem? The header _should_ be being sent for both pre-flight and regular requests. Could you screenshot the failing network request from the devtools, including the sent and received headers?

**Comment by alanshaw** [comment]
ping @glitch003

**Comment by hugomrdias** [comment]
I can’t reproduce this error, we need more information to understand whats happening on your side. We have the headers for CORS permissive enough for this to work.

I'm going to close this for now, but please re-open this with more info and we will try to help.
