### ISSUE TITLE
upload limit

### ISSUE THREAD

**Issue by Bentoon** [ipfs-shipyard/nft.storage#171]
Hello
First : Thanks so much! this is a great idea. 
Especially as more NFT's become Spatial (3D & XR) and Interactive! But as these are not Still images or videos, they require more storage.
I make interactive graphic novel NFT's for touchscreen & XR with WebGL. 
https://gateway.pinata.cloud/ipfs/QmVAsUUfWeuNrdfbNRxx5rwWEDyK2CiaBqUo99t5DLp8Mx/
I usually use IPFS Pinata  & ARweave but I really think you could nail this!

Anyway please let me know. I would love to proselytize,
Thanks,
Jb

**Comment by alanshaw** [comment]
Hey @Bentoon I've just opened an [issue](https://github.com/ipfs-shipyard/nft.storage/issues/173) to track this endeavour - we're working on increasing the limit asap.
