### ISSUE TITLE
Increase 100MB upload limit

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/nft.storage#173]
The 100MB upload limit currently exists because nft.storage is hosted on Cloudflare and this is the upload limit for workers.

We plan to increase (or maybe even remove) this limit asap.

In order to enable parallel uploading and minting of NFTs we're first going to [enable CAR file uploads](https://github.com/ipfs-shipyard/nft.storage/issues/172) and then do the work to support chunked CAR uploads (we currently have a MVP [library for CAR chunking](https://github.com/alanshaw/carbites)).

**Comment by Bentoon** [comment]
Amazing! @alanshaw Thanks & keep me in Loop. Much obliged
