### ISSUE TITLE
Help request IPFS pinning

### ISSUE THREAD

**Issue by flatout** [ipfs-shipyard/nft.storage#177]
Hello, I created an NFT on Zora but need to edit the metadata. I read your notice that NFT.storage could be used as a pinning service on IPFS.

Do you have some instructions or tutorial on where on the IPFS site I set nft.storage and how I edit the Etherscan doc?

Thank you.

**Comment by alanshaw** [comment]
There's some brief docs on adding nft.storage as a _remote_ pinning service here https://nft.storage/#configure-as-a-remote-pinning-service

...I'm not certain this is what you need.

I can't really speak to how you edit metadata for an NFT you created on Zora. In IPFS, data is immutable (although there are some existing functionalities to make things appear mutable as well was some things currently in the pipeline), that said, if you need to update metadata then from the point of view of off-chain storage, you can just need to upload a new version of the metadata.json to nft.storage, and then update the token URI for the contract on-chain to point to the new CID. I don't know how you'd necessarily do that via Zora though.

**Comment by alanshaw** [comment]
Please reopen if there's something else we can help with.
