### ISSUE TITLE
Cannot Store Blob Data

### ISSUE THREAD

**Issue by baxterjfinch** [ipfs-shipyard/nft.storage#179]
No matter what I try, I cannot store a json Blob, even with plain-text.

Example in documentation here also does not work: 

https://github.com/ipfs-shipyard/nft.storage/blob/e619a85a818417a9f045c43816a977c3a9975595/packages/client/examples/node.js/storeBlob.js

I also cannot store a simple string. 

Error received:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received an instance of Uint8Array
    at write_ (_http_outgoing.js:670:11)
    at ClientRequest.write (_http_outgoing.js:638:15)
    at Readable.ondata (_stream_readable.js:708:22)
    at Readable.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Readable.push (_stream_readable.js:214:10)
    at next (internal/streams/from.js:51:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Readable instance at:
    at emitErrorCloseNT (internal/streams/destroy.js:75:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Attempted with Node versions:
10.15.3
12.18.3
13.11.0

**Comment by alanshaw** [comment]
We're targeting Node.js 14 and 16 - would you mind trying with one of those versions?

**Comment by baxterjfinch** [comment]
Thanks, I'll try that.

Im also uploading a <Buffer> as an image and I don't see the image. This is the metadata uri:

https://bafyreihplvtc5uyk7dqcsehn6hlanzwelsytd7l4n5pbj2effjvqcj2giu.ipfs.dweb.link/metadata.json

and the image uri in the metadata shows:

https://bafybeibgclvtqrlopwx5sohrtzxgwx3ar627cfsrsbyqzg5z62vc3luuje.ipfs.dweb.link/pla0.jpg

This is the call:

```
client.store({
      name: token.name,
      description: token.description,
      image: new File(picture, `${token.name}.jpg`, { type: 'image/jpg' }),
      properties: token
    })

```

where `picture` is of type <Buffer>

However the image uri just shows a white page

**Comment by alanshaw** [comment]
The [`File` constructor](https://developer.mozilla.org/en-US/docs/Web/API/File/File) takes an array of buffers, try:

```js
new File([picture], `${token.name}.jpg`, { type: 'image/jpg' })
```

**Comment by baxterjfinch** [comment]
Amazing, thanks!
