### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by hugomrdias** [ipfs-shipyard/nft.storage#181]
This issue will help track all the tasks needed to migrate to FaunaDB

- [x] Analise all the KVs and code to figure out the best structure to store in FaunaDB
- [x] Build a pipeline to download all the KV data to a local LevelDB
- [x] Build a basic pipeline to upload local LevelDB data to FaunaDB
- [ ] WIP Test out FaunaDB queries
- [x] WIP Test out FaunaDB aggregations
- [x] Build validation into the pipeline to make sure the structure of each NFT is valid and in sync with Cluster and Pinata
- [ ] Build final transformation to be stored in FaunaDB and make sure the pipeline can properly sync NFT data from CF to Fauna.
- [ ] Figure out what’s the best way to rewrite the Pinata Queue using FaunaDB
- [ ] Write a Fauna "client" with all the queries that we need to rewrite the API routes
- [ ] Check which CRON jobs we still need and either remove or rewrite using the Fauna client
- [ ] Figure out what to do with the users KV
- [ ] Tokens probably need improving to allow to permissions by route, so we can create some admin route

**Comment by dchoi27** [comment]
@hugomrdias should we close this or is it still useful?

**Comment by alanshaw** [comment]
Superseded by https://github.com/ipfs-shipyard/nft.storage/issues/331
