### ISSUE TITLE
how do we do aggregate state / stats

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/nft.storage#184]
TODO: Document discussion that happened on how do we go about it.

**Comment by Gozala** [comment]
Unlike traditional SQL databases Fauna does not have an effective way to query aggregate states e.g could documents in the collection (equivalent of counting records in table). We have identified two different ways to overcome this challenge that require different tradeoffs:

1. Faunas official blog post suggests [Using ACID Transactions to Combine Queries and Ensure Integrity](https://fauna.com/blog/using-acid-transactions-to-combine-queries-and-ensure-integrity). This in nutshell boils down to enforcing invariant at API level, that is writing custom User Defined Functions (UDF)s and using those instead of creating documents directly. In other words if you we have a collection `Tokens` and we want to track number of tokens in it, we could define functions like `addToken` / `removeToken` which would update counter in some known document in `TokenCount`  collection.
   - 💔 Biggest challenge here is knowing everything you'll need to aggregate ahead of time. If requirements change (and they will) we may find our self in position where we stored bunch of tokens and were not counting them because such requirement did not existed.
      > Note: In practice aggregate state can be a lot more complex than simple count.
   - 💔 Oversight in the code base could lead to some unaccounted documents been added or removed. Since there is practical way to restrict how documents in collection are added / removed / edited all we have at our disposal is a discipline.
   - 💔 GraphQL interface generates CRUD endpoints for each collection that would just sidestep our custom functions that deal with state aggregation.
      > Note: We could override their implementations so they just error, but again all we have a discipline to ensure we don't miss anything.
   - 💚 Aggregate state is fully in sync and updated in the same transaction.

2. It is possible to compute aggregate state retroactively as a reduction. Idea here is to have extend documents in the collection with an optional field that is ref to document holding an aggregate state. This way UDF could go over documents that have not been accounted for call a reducer with current aggregate state and non accounted document and update both aggregate state and a document by adding a ref to an aggregate to it.
   - 💚 Aggregate states could basically be written as reduce functions
   - 💚 Once requirements change it's easy to just create a new reducer function to aggregate new state that was not planned in initial schema.
   - 💔 Aggregate state is not in sync with rest of the state and is usually behind, making it not fit for cases where strong consistency is needed.
   - 💔 Not triggered automatically, so UDF doing aggregation needs to be triggered from external source e.g. CRON job somewhere (e.g. github CI).


I personally find No 1 to be too error prone, and really challenging in the face of changing requirements as there is no obvious way to introduce new aggregate state that would account for all the existing data. No 2 on tho other hand is more flexible, we do not need a strong consistency for stats and while external trigger is a downside it is not a show stopper.

**Comment by dchoi27** [comment]
Should we close this given no more Fauna?
