### ISSUE TITLE
[Feature Request] Could we add metadata such as title in nft.storage, so we can remember it better?

### ISSUE THREAD

**Issue by askender** [ipfs-shipyard/nft.storage#188]
As a user, I think it is useful feature.

As a dweb developer, I think NFT is one of the choices. People can make the data public and still mint the NFT and sell License.
I'm developing a dweb search engine:  https://dweb-search.on.fleek.co
Hope we can cooperate in the future.  (you can found me(same name) in filecoin-slack)

**Comment by alanshaw** [comment]
🙏 do you have a proposal for metadata?

The off-chain part of NFTs (the part that nft.storage deals with) are a metadata file and a image/video (typically). The metadata file _should_ have a `name` property and possibly a `description` to comply with the ERC721 and ERC1155 specs for NFTs. Can you use this information in your search engine?

See "ERC721 Metadata JSON Schema": https://eips.ethereum.org/EIPS/eip-721

**Comment by askender** [comment]
a proposal for metadata:    https://github.com/anwen/dweb-search/wiki/A-proposal-for-metadata-which-support-NFT-and-other-kinds-of-non-fungible-assets

Yes, name and description is basic, optional we can add `authors` (wallet info can be used as a donation address), `license`, `asset_type`

The key info:
- if nft.storage has `name` field, it is good for users who have a lot of NFTs, easier to remember.
- If `license` is added and it is public. We can get metadata.json directly from nft.storage
- non fungible assets have other forms beyond NFT(standards: ERC-721 & ERC-1155)
- I wish people can add articles as non fungible assets which they can use all kinds of licenses.

A example:
- This NFT is also public as a pdf in ipfs: https://qiwa.re/scale/wuhan/  which has detail NFT license info:
- **Limited editions of that file have also been published as nonfungible tokens (NFTs). Token holders can:**
    • create derivatives of the work (printed editions, translations,
etc)
    • transfer or sell the token with these additions
    • issue new tokens based on the derivatives

**Comment by dchoi27** [comment]
Hey there - this would be something difficult to enforce at the nft.storage level. For your product, it's probably something better enforced at the token standard level (e.g. modifying ERC-721), or potentially if enough people organically add specific custom fields to their own NFT's metadata. But unless the former case happens, it's not something in-scope for nft.storage.

Thanks!
