### ISSUE TITLE
Currently upload blob claims that file was pinned which may not be true

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/nft.storage#191]
Here is the code

https://github.com/ipfs-shipyard/nft.storage/blob/fe2f969876e9509f1aef80dd3322ae476d68582a/packages/api/src/routes/nfts-upload.js#L57-L72

When cluster adds it may not be pinned it maybe different.

**Comment by alanshaw** [comment]
Not sure I follow?

**Comment by Gozala** [comment]
Line 57 does not guarantee that content was pinned it may be queued or fail, yet on line 70 we set status to pinned. @hugomrdias noticed inaccurate pin states during data migration which we think might be attributed to this.

**Comment by alanshaw** [comment]
> Line 57 does not guarantee that content was pinned

Wait, really? I was under the impression that add only responds after content has been added to the cluster.

@hsanjuan is it possible to send data to the `/add` endpoint, receive a successful response with a CID and for it to not be pinned?

@Gozala I'm aware of an issue where if cluster reports a pin status as failed then we don't re-check with cluster, meanwhile cluster will keep trying to pin it forever, so it could eventually become pinned - could this be the issue that @hugomrdias saw?

**Comment by hsanjuan** [comment]
> @hsanjuan is it possible to send data to the `/add` endpoint, receive a successful response with a CID and for it to not be pinned?

Well yes, since the pinning part is async. You may add and finish that request, but the item is queued while other things are pinning.
