### ISSUE TITLE
Surface deal data selector in client

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/nft.storage#192]
The deal data selector is now available so if folks actually want to retrieve data from Filecoin they'll soon be able to use this (🔜 currently needs custom lotus client https://github.com/filecoin-project/lotus/pull/6393).

![image](https://user-images.githubusercontent.com/152863/122448788-0a075580-cf9d-11eb-8faf-e132748928d2.png)

**Comment by askender** [comment]
How to get  the  real `deal data selector`  ?     such as ` /Links/0/Hash` ?
How did you generate the image you posted?  @alanshaw 

I didn't find the doc related to `--data-selector`.
