### ISSUE TITLE
Browser example fails with CORS

### ISSUE THREAD

**Issue by vasco-santos** [ipfs-shipyard/nft.storage#193]
Running the [browser example to upload CAR](https://github.com/ipfs-shipyard/nft.storage/tree/main/packages/client/examples/browser/car) with production nft.storage returns a CORS error with a production API Token

cc @olizilla

**Comment by olizilla** [comment]
hmm, i got this as well, but now I don't, I can use the browser car example against prod without issue. It uses the same endpoint `/upload` which has CORS headers set https://github.com/ipfs-shipyard/nft.storage/blob/630a611eda8faa24e6e49d0781381d81cd1e242c/packages/api/src/index.js#L74

**Comment by alanshaw** [comment]
Needs HTTPS - I'm submit a PR
