### ISSUE TITLE
filecoin calibration reset

### ISSUE THREAD

**Issue by wangzhuo-or-json** [ipfs-shipyard/nft.storage#211]
After filecoin calibration is reset, does the file data stored on nft.storage still exist?

**Comment by ribasushi** [comment]
Yes, 1000%. Data in `nft.storage` is backed up in multiple ways and no single event can cause eve one of its CIDs go away.

The "calibration reset" you are referring to is the reset of one of the many filecoin **non-production test networks**. nft.storage does not store anything there in the first place, we only use mainnet miners.
