### ISSUE TITLE
import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').

### ISSUE THREAD

**Issue by anudit** [ipfs-shipyard/nft.storage#215]
Hey, I am running into this error when using,
`"nft.storage": "^3.0.1",` 
`"next": "^11.0.1",`
`"webpack": "^5.40.0"`

```
info  - Creating an optimized production buildFailed to compile.
./node_modules/@ipld/car/esm/lib/decoder.js 
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').

> Build error occurredError: > Build failed because of webpack errors
    at D:\Users\anudit\Documents\Github\convo\node_modules\next\dist\build\index.js:15:924    at async Span.traceAsyncFn (D:\Users\anudit\Documents\Github\convo\node_modules\next\dist\telemetry\trace\trace.js:6:584)error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Build works fine on version `"nft.storage": "^2.1.1",`

**Comment by olizilla** [comment]
Can you give any more details on your setup, particularly the webpack config? can you point us to a repo? I've just created a minimal next.js 11 example app that includes the nft.storage client and the prod build works without error

```console
$ npm run build

> next-example@0.1.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Page                                Size     First Load JS
┌ ○ /                               23.5 kB        87.1 kB
├   └ css/ea6f1f42cebc7b8cbe53.css  675 B
├   /_app                           0 B            63.6 kB
├ ○ /404                            3.17 kB        66.8 kB
└ λ /api/hello                      0 B            63.6 kB
+ First Load JS shared by all       63.6 kB
  ├ chunks/framework.64eb71.js      42 kB
  ├ chunks/main.1f18f7.js           20.2 kB
  ├ chunks/pages/_app.11bd90.js     555 B
  ├ chunks/webpack.61095c.js        810 B
  └ css/01db3197b29cb52779ce.css    203 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

**Comment by anudit** [comment]
Here is the repo, https://github.com/anudit/convo, `yarn build` works fine on it.

After upgrading to `"nft.storage": "^3.0.1"`, I run into the above error.

**Comment by olizilla** [comment]
> Here is the repo, https://github.com/anudit/convo, yarn build works fine on it.

I've cloned the default branch of https://github.com/anudit/convo and run
```
yarn
yarn build
```
and i get a bundle error:

```
$ yarn build
yarn run v1.22.10
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Checking validity of types  
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /Users/oli/Code/anudit/convo/node_modules/next-pwa/register.js
> [PWA] Service worker: /Users/oli/Code/anudit/convo/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
TypeError: Cannot read property '0' of undefined
    at Function.decode (/Users/oli/Code/anudit/convo/node_modules/multibase/src/index.js:62:22)
    at Object.privateKeyFromString (/Users/oli/Code/anudit/convo/node_modules/@textile/crypto/dist/cjs/utils.js:139:41)
    at Function.fromString (/Users/oli/Code/anudit/convo/node_modules/@textile/crypto/dist/cjs/keypair.js:271:39)
    at getClient (/Users/oli/Code/anudit/convo/.next/serverless/chunks/255.js:28:73)
    at getAllThreads (/Users/oli/Code/anudit/convo/.next/serverless/chunks/255.js:37:28)
    at getStaticPaths (/Users/oli/Code/anudit/convo/.next/serverless/pages/thread/[threadId].js:87:60)
    at buildStaticPaths (/Users/oli/Code/anudit/convo/node_modules/next/dist/build/utils.js:16:86)
    at /Users/oli/Code/anudit/convo/node_modules/next/dist/build/utils.js:26:628
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/oli/Code/anudit/convo/node_modules/next/dist/telemetry/trace/trace.js:6:584) {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

this is before i upgrade the `nft.storage` dep.

**Comment by anudit** [comment]
Yeah @olizilla, it needs the .env secrets to build. I guess I'll triage on it a bit more get back soon.

**Comment by anudit** [comment]
1. A fresh install of `node_modules` didn't help.
2. I can't reproduce the error on your [minimal repo](https://github.com/nftstorage/nft.storage-example-next.js) using `3.0.1` and the same next/webpack config.
3. Downgrading to `2.1.1` from `3.0.1` fixes the error on my repo.
4. 'decode' is exported from '@ipld/dag-cbor', I checked.

No clue why, I'll stick to `2.1.1` for now.

**Comment by bennyvenassi** [comment]
Hey,
I got the same issue while using nft.storage in an Angular 12 Project. With 2.1.1.  I can compile the project.

**Comment by alanshaw** [comment]
🙏 we need some code that reproduces the problem so we can look into it - @bennyvenassi can you help?

**Comment by bennyvenassi** [comment]
> 
> 
> 🙏 we need some code that reproduces the problem so we can look into it - @bennyvenassi can you help?

I tried to replicate the issue in a clean angularproject with only nft.storage in it. And... it compiles without any errors.
In my "main" project, where I use ethers, web3modal, etc. i still get the error.

And of course, you can take a look into my code. I'll attach you both "projects".

[nftstorage.zip](https://github.com/ipfs-shipyard/nft.storage/files/6754607/nftstorage.zip)

**Comment by nickadamson** [comment]
@alanshaw @anudit I actually ran in to this problem yesterday. I didn't even get so far as to figure out that nft.storage had the '@ipld/dag-cbor' dependency, ha. What worked for me was 1) delete node_modules folder 2) delete package-lock.json 3) run npm install

You might want to add a step 2.5) check package.json and make sure nft.storage version matches the most recent at https://www.npmjs.com/package/nft.storage. So:  _"nft.storage": "^3.0.1"_

**Comment by anudit** [comment]
I was able to upgrade to the latest version and have gotten no issues so far.

**Comment by fungilation** [comment]
Why is this issue closed? It's reproducible with Next build. Deleting node_modules and reinstalling with `yarn` does not fix:

```
Failed to compile.

./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').


> Build error occurred
Error: > Build failed because of webpack errors
```

The culprit is the `@ipld/dag-cbor` dep. After I downgraded nft.storage from 3.3.0 to 2.1.1, this is a diff in `yarn.lock`:

![Screen Shot 2021-09-30 at 10 20 52 PM](https://user-images.githubusercontent.com/3803466/135569418-374c28f0-f56b-44f9-b42f-14bf2f1014e2.png)

With `@ipld/dag-cbor` gone, `next build` runs fine then.

**Comment by sicktastic** [comment]
I am trying all different versions—no luck so far.  Did downgrading to 2.1.1 work?

**Comment by fungilation** [comment]
> After I downgraded nft.storage from 3.3.0 to 2.1.1
Works for me.

BUT, the big downside afaik: 2.x has upload size limit of 100 MB. 3.x with chunked uploads can go up to 32 GB.

So, please please make 3.x usable. Either `@ipld/dag-cbor` fixing itself, or replace it as a dependency.

**Comment by nickadamson** [comment]
> Deleting node_modules and reinstalling with `yarn` does not fix:

have you tried using npm as your package manager? I only get this issue when using yarn

**Comment by fungilation** [comment]
Tried `npm run build` after `rm -rf node_modules`, `npm install nft.storage@latest`. Still get this

```
$ npm run build

> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Creating an optimized production build
Failed to compile.

./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').


> Build error occurred
Error: > Build failed because of webpack error
```

**Comment by sicktastic** [comment]
I was able to fix this by moving some packages.  For me, it was @pinata/sdk—as I was testing a few different NFT libraries.

**Comment by fungilation** [comment]
I don't have `ethereum-erc721` dependency.

And my project is pretty barebone. The fact that the only fix for me so yarn build works is downgrading only `nft.storage`, and only that from 3.x to 2.x, is telling on it alone and its associated dependencies is at issue.

Namely, `@ipld/dag-cbor`

**Comment by rvagg** [comment]
Folks, if you're still running into this problem please take discussion to https://github.com/ipld/js-dag-cbor/issues/37 - we're trying to figure out exactly what combinations of tooling is causing this problem. Getting libraries to play nicely with _all_ of the various compilers and toolchain pieces for server & browsers is quite a pain and we appear to be running into something very specific here but it seems to be quite hard to replicate. So your help in narrowing down the exact, and minimal combination of tools and steps to trigger the problem would be helpful.

**Comment by scottbolasevich** [comment]
> > Deleting node_modules and reinstalling with `yarn` does not fix:
> 
> have you tried using npm as your package manager? I only get this issue when using yarn

is there any other options?
