### ISSUE TITLE
client.store function results in a file containing ipfs cat /ipfs/<CID>/: unknown node type

### ISSUE THREAD

**Issue by zangezi39** [ipfs-shipyard/nft.storage#216]
I am trying to upload a jpg file using the store() but keep getting a text file containing: *ipfs cat /ipfs/<CID>/: unknown node type*. The function is below:

    const metaData = await client.store({
        id: _tokenId,
        name: this.state.tokenTitle,
        description: this.state.tokenDescription,
        image: new File(["file"], 'SurNFT-1.jpg', { type: "image/jpg", }),
    });

**Comment by alanshaw** [comment]
"file" should be replaced with your file data

**Comment by alanshaw** [comment]
@zangezi39 did this solve the issue for you?

**Comment by zangezi39** [comment]
Thank you very much for your response! Unfortunately, no, - I am able to do the client.storeBlob for both the jpeg and he metadata json, but client.store() is giving me the same result. I am quite new to this, so perhaps I am making some basic mistake. Here is the code:

    const uploadFiles = document.getElementById("input-file").files;
    const uploadName = uploadFiles[0].name
    const metaData = await client.store({
        id: _tokenId,
        name: this.state.tokenTitle,
        description: this.state.tokenDescription,
        image: new File([uploadFiles[0]], uploadName, { type: 'image/jpeg' }),
    });

What am I doing wrong?

Thanks again.

**Comment by alanshaw** [comment]
Maybe try this?

```js
const uploadFiles = document.getElementById("input-file").files;
const metaData = await client.store({
    id: _tokenId,
    name: this.state.tokenTitle,
    description: this.state.tokenDescription,
    image: uploadFiles[0],
});
```

**Comment by zangezi39** [comment]
It worked! Simple and beautiful :) 

Thank you very much!
