### ISSUE TITLE
GB

### ISSUE THREAD

**Issue by wantedpixelmaza** [ipfs-shipyard/nft.storage#219]
Hello!)Tell me pls how much GB i can store ?

**Comment by jnthnvctr** [comment]
Hi, 

This is a service to provide free storage for nfts. As such, there isn’t a hard cap on the account size (part of our goal is to enable new use cases in NFTs like HD video, AR/VR assets), but we actively monitor the usage, and will be reaching out to folks to confirm the stored content is mapping to nfts (or an actual nft business) to make sure the service isn't being abused. We also have automated checks we’re using to verify against major blockchains that the CIDs are indeed getting pushed into NFTs. 

We’re working on a separate service that will support non-nft use cases soon, so if you're just looking for user-friendly storage that may be a better option!
