### ISSUE TITLE
CID V1 Calculation Incorrect?

### ISSUE THREAD

**Issue by skogard** [ipfs-shipyard/nft.storage#222]
Hi, it looks like the CID nft.storage stores the files under may be incorrect. It is not consistent with the actual CID v1 locally calculated from the file. Maybe I'm missing something, but this seems pretty straight forward.

Basically what's happening:

1. I compute the cid (v0)
2. I convert it into v1
3. Then I upload the same content to nft.storage and get the response back.
4. I compare the nft.storage stored filename vs. the computed v1 cid.
5. They don't match.

Here's the replicable code (Be sure to replace the `process.env.API_KEY` with your nft.storage API_KEY:

```
const { NFTStorage, File } = require('nft.storage')
const fs = require('fs')
const Hash = require('ipfs-only-hash')
const CID = require('cids')
const apiKey = process.env.API_KEY
const run = async () => {

  const str = "hello world"
  
  // get cid v0
  const v0 = await Hash.of(str)
  console.log("v0", v0)

  // convert to v1
  const v1 = new CID(v0).toV1().toString("base32")
  console.log("expected v1", v1)

  // Upload to NFT.STORAGE
  const client = new NFTStorage({ token: apiKey })
  let response = await client.storeBlob(Buffer.from(str))
  console.log("actual v1 returned by nft.storage", response)
}
run()
```

When I run it, I get:

```
v0 Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD
expected v1 bafybeihykld7uyxzogax6vgyvag42y7464eywpf55gxi5qpoisibh3c5wa
actual v1 returned by nft.storage bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e
```

You can see the "expected v1" and "actual v1 returned by nft.storage" do not match.

I first thought I was doing something wrong, but I tried it on https://cid.ipfs.io/#Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD and it looks like my locally computed cid IS correct.

What is going on?

**Comment by alanshaw** [comment]
Yes this can be confusing but it's consistent with output from `ipfs add` when v1 CIDs are enabled:

```console
$ echo -n "hello world" | ipfs add
added Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD
 
$ echo -n "hello world" | ipfs add --cid-version=1
added bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e
```

In IPFS when you enable v1 CIDs, you also implicitly enable an option called "raw leaves". The option saves some bytes in the generated DAG by not wrapping leaf nodes in a UnixFS protobuf. You can explicitly opt out of raw leaves like this to get the v1 CID you're converting to in your example above:

```console
$ echo -n "hello world" | ipfs add --cid-version=1 --raw-leaves=false
added bafybeihykld7uyxzogax6vgyvag42y7464eywpf55gxi5qpoisibh3c5wa bafybeihykld7uyxzogax6vgyvag42y7464eywpf55gxi5qpoisibh3c5wa
```

**Comment by skogard** [comment]
Oh got it! I finally got it to match by adding the rawleaves option. Thank you!
