### ISSUE TITLE
Use dnsaddr to find ipfs-cluster multiaddrs

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/nft.storage#259]
Rather than passing in the full multiaddrs at deploy time:

https://github.com/ipfs-shipyard/nft.storage/blob/b93614ece6806611addea215726ff43f5f7f98bc/packages/api/wrangler.toml#L22

Consider using the dnsaddr `/dnsaddr/nft.storage.ipfscluster.io` so we have the flexibility to drop and reprovision cluster nodes without having to redeploy the api.

```
ipfs swarm connect /dnsaddr/nft.storage.ipfscluster.io
connect 12D3KooWCRscMgHgEo3ojm8ovzheydpvTEqsDtq7Vby38cMHrYjt success
connect 12D3KooWQtpvNvUYFzAo1cRYkydgk15JrMSHp6B6oujqgYSnvsVm success
connect 12D3KooWQcgCwNCTYkyLXXQSZuL5ry1TzpM8PRe9dKddfsk1BxXZ success
```

see: https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md

**Comment by olizilla** [comment]
Of note, pinata backup can fail if you pass it a multiaddr as an origin that it can't connect to

> ⚠️ Please make sure every node provided is online. Pinata will attempt to connect to all nodes before pinning the content, and if any these nodes are offline, your request will eventually fail.
– https://github.com/PinataCloud/Pinata-SDK#host-node-multiaddresses

**Comment by dchoi27** [comment]
We're not sending multiaddrs anymore! Closing
