### ISSUE TITLE
IPFS pin with nft.storage stuck

### ISSUE THREAD

**Issue by adriadrop** [ipfs-shipyard/nft.storage#261]
I am using CLI (on latest ubuntu) to pin directory and files to nft.storage but it always gets stuck. Using command like

`ipfs pin remote add  --name=no7 --service=nft-storage QmcWYGJ6tMxLNgBTYyiwhYR8PrweWq9h9VtzyhttGfrV3p`

and it stays like this forever. When I check nft.storage files section on web it shows hashes but with 0 KBs, any ideas what is wrong and what to do/how to pin files and directories using  this service.  

![image](https://user-images.githubusercontent.com/8969767/126519066-93926bd6-0985-4eb9-bf81-dd68b8810f41.png)

**Comment by alanshaw** [comment]
Hi @adriadrop, looking at the status check API the CID you listed is pinned properly and has a size:

https://api.nft.storage/check/QmcWYGJ6tMxLNgBTYyiwhYR8PrweWq9h9VtzyhttGfrV3p

We have a backlog of updates to the index for the files listing that's causing sizes to not show up for a while after they've been uploaded. We're migrating to a different database that will resolve this problem, apologies for the inconvenience.

**Comment by ZhangPeibin** [comment]
@alanshaw Hi , how long it will be ok ? I check ten mins but it also size=0

**Comment by adriadrop** [comment]
@alanshaw ok this is just web UI problem that is constant. I have more of a problem with ipfs CLI pinning where I run command as I said and it hangs there forever so I am not sure did something get pinned or not. I can use your URL above and see then, but that is kind of suboptimal or buggy  way to check.

Now I have this I tried to pin https://api.nft.storage/check/Qmcxu5Rk3XTz5AiG438GRwbH8szDEUFUqni4RwZequRoLf which says failed and not queued 
![image](https://user-images.githubusercontent.com/8969767/126904059-7615e00b-50c1-4ff7-b9eb-2a82ac59da5f.png)
and there is another one that says failed but also queued
![image](https://user-images.githubusercontent.com/8969767/126904092-d3c9715d-b30a-4019-a03c-2c5fdf3b2b1b.png)

Wondering what to think od that and what happened?

**Comment by adriadrop** [comment]
I made this one again https://api.nft.storage/check/QmUfo84ktFrcrdL423BaQhXt2JngazRwhC6nfn1vzm4epo

it is queued now, wondering when it can be pinned or when it will be failed and why could it fail as some other did?

**Comment by ribasushi** [comment]
@adriadrop your CID is currently advertised as available from a single source: `12D3KooWSwbezPPycGg5ZKFyqHkzd7HYm9fmr2gh3ptaw21qSBDr`

I can not dial it from the internet:
```
~$ ipfs swarm connect /p2p/12D3KooWSwbezPPycGg5ZKFyqHkzd7HYm9fmr2gh3ptaw21qSBDr
Error: connect 12D3KooWSwbezPPycGg5ZKFyqHkzd7HYm9fmr2gh3ptaw21qSBDr failure: failed to dial 12D3KooWSwbezPPycGg5ZKFyqHkzd7HYm9fmr2gh3ptaw21qSBDr:
  * [/ip4/78.1.80.246/tcp/64546] dial tcp4 0.0.0.0:4001->78.1.80.246:64546: i/o timeout
  * [/ip4/78.1.80.246/udp/64546/quic] timeout: no recent network activity
```

It might be a nat traversal issue or something else, but the bottom line is that the service can't get to the content to pin it. What are the details of what serves on your end?

**Comment by adriadrop** [comment]
@ribasushi hmm maybe I am using this wrong? Do I need to run it like this. Having IPFS daemon or IPFS desktop running while it use **ipfs add** and then also while I use **ipfs pin**. Because I was thinking that I can just fire these commands and it would get propagated somewhere but maybe I need to first have it locally available so others can pick it up?

**Comment by ribasushi** [comment]
The latter. The "propagate somewhere" is exactly the process of "pinning". IPFS is a **strictly pull-based network**: a node (this includes you) never hosts anything from anyone else (even shards of that) *unless* you actively requested it. For the nft.storage infra to preserve your content you either need to just upload it or you must:
1. make it available via a dht-enabled ipfs node
2. request nft.storage to pull it from you ( "pin" )
3. keep the content available long enough for nft.storage to report "I got this now"

**Comment by ribasushi** [comment]
cc @ZhangPeibin

**Comment by adriadrop** [comment]
@ribasushi  makes sense, but I didn't think it through before. I just went "lets pin this"  and since CLI doesn't check can it do that and is content available it just goes like it can be pinned.  Not sure does it make sense to make a note/message for people while pinning that content needs to be available or that daemon needs to be live.  thnx on help.

**Comment by adriadrop** [comment]
@ribasushi one more question, when will NFT.storage stop trying to pull data and mark pin as failed, meaning when will it timeout. Lets say I pinn something now and go out and my computer goes into suspend and daemon is not active, will it fail or will it continue later, how does this process goes?

**Comment by ribasushi** [comment]
@adriadrop we don't have a definitive SLA defined around this yet, but "long". There are several parts of the system, the one I am responsible will keep (re)trying for several days.

What time-frame do would you consider reasonable? Let us know and we will discuss this internally tomorrow and put in place something definitive.

**Comment by adriadrop** [comment]
@ribasushi I have another situation. So I added again the QmUfo84ktFrcrdL423BaQhXt2JngazRwhC6nfn1vzm4epo  CID (which is a directory with files) I have running it on a local node and I can see the files and directory. So it should be available. So I run ipfs pin with nft.storage service and it started pinning or at least it said here https://api.nft.storage/check/QmUfo84ktFrcrdL423BaQhXt2JngazRwhC6nfn1vzm4epo  pinning. 
So I left the computer running but it went to suspend after some time, now I came back and I see status failed. So wondering why it went to failed so fast, If I understood you correctly it shouldn't go to fail so fast but retry until it gets all files? Trying to know more what to expect and how it really works....

**Comment by ribasushi** [comment]
@adriadrop the retry is not in-process. It is a cron-like thing, that will go back through "ok... what is there that I don't yet have... let's try again". It will swap to "pending for filecoin inclusion" shortly[1], the system that updates the pin-status ( separate ) may lag a bit: we are in the process of migrating things so that the updates are even more timely/precise.

In short: our status APIs are in the final stretch of getting revamped to be reliable and timely indicators of state, we are just not quite there yet. In the meantime the core premise of `nft.storage` is online and operational: if you run `ipfs dht findprovs {{yourcid}}` you will see a number of peers who are "not you" advertise it: this is us having fully retrieved your CID and providing it to the world to retrieve on demand.

[1] Usually within 10 minutes, but this is *also* a component in flux right now, should resume normal operation late tonight .

**Comment by adriadrop** [comment]
@ribasushi  

About that last thing you said, I am running this command
**ipfs dht findprovs Qmcxu5Rk3XTz5AiG438GRwbH8szDEUFUqni4RwZequRoLf**
12D3KooWSwbezPPycGg5ZKFyqHkzd7HYm9fmr2gh3ptaw21qSBDr
12D3KooWSGCJYbM6uCvCF7cGWSitXSJTgEb7zjVCaxDyYNASTa8i
12D3KooWNyeZ6jSaNdHU2BRPFDADg2LWyuxHrASpvRq1T5hGqga2

it shows 3 peers first is mine 2 others are not, but when I shut down a mine I couldn't retrieve files for some 20 minutes
https://ipfs.io/ipfs/Qmcxu5Rk3XTz5AiG438GRwbH8szDEUFUqni4RwZequRoLf

Now, 30 min lateer I can, but it took some time to propagate on internet  I can guess. So it seems it works but the status still says failed
https://api.nft.storage/check/Qmcxu5Rk3XTz5AiG438GRwbH8szDEUFUqni4RwZequRoLf

So it is really kind of confusing and hard to know what is going on and the only real method of checking at real time does it work is to shut off my node and try to open URL which is kind of too rudimentary, hopefully, it gets better as you said :)
