### ISSUE TITLE
Support different MIME types for NFTs

### ISSUE THREAD

**Issue by talentlessguy** [ipfs-shipyard/nft.storage#265]
Sorry if this was opened before, I tried searching "mp3" / "non-image" etc in issues and nothing showed up.

So, I'd like to propose multiple formats support, but ofc not all of them not to spread malware. I think allowing a list of videos / music also would be nice, e.g. those starting with `video/` and `audio/`.

I'm building an audio NFT project but sadly I cannot use nft.storage since MIME type for an mp3 file is `audio/mp3`.

Is it a bad idea or it's ok?

**Comment by nickadamson** [comment]
@talentlessguy you can upload whatever file you want AFAIK. https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/examples/node.js/storeBlob.js try this first.
