### ISSUE TITLE
Is it possible to pin using node js  ?

### ISSUE THREAD

**Issue by david-dacruz** [ipfs-shipyard/nft.storage#268]
Hi I'm looking to pin thousands of cids is it possible using your javascript api ? Also if you choose to discontinue service for whatever reason, what happens to the original content uploaded on ipfs is it still available with the same hash so that I can pin it myself ?

**Comment by BaRRaKudaRain** [comment]
Your uploaded content will remain in IPFS, so it still will be available.

**Comment by dchoi27** [comment]
Yes, but only NFT data (images, metadata, assets that are found in an NFT on a chain). If the service gets discontinued we'll let you know and you can pin yourself!
