### ISSUE TITLE
Trying to upload a 2.57 GB folder through node to NFT.Storage

### ISSUE THREAD

**Issue by JohnnyBDesign** [ipfs-shipyard/nft.storage#275]
Trying to upload a 2.57 GB folder through node to NFT.Storage into the same directory. I know the upload limit is 100MB, however can I break that up into smaller upload portions into the same directory?  Confused as to how large 10k Generative NFT collectibles store images on IPFS, if anyone could help that would be great! (Already tried Pinata and it did not work)

**Comment by BaRRaKudaRain** [comment]
Somwhere in issues I saw that there's no upload limit on CAR files. So you can pack files into the CAR (_Content-Addressed ARchive_). Just go to [this link](https://car.ipfs.io/) pick some files and upload it to NFT.Storage. Hope it would be helpful.

**Comment by dchoi27** [comment]
^ agreed this is the best way. Let us know if any questions!
