### ISSUE TITLE
Stopped Working: long upload, small byte size and no image data

### ISSUE THREAD

**Issue by mattlockyer** [ipfs-shipyard/nft.storage#279]
Was working fine past couple of days. Now everything I upload has 126/7 bytes size and this response:
https://bafyreie7bylryvuefkr5csewwefpnju4pxfjnyd3b6wpnw7udwlhffz2se.ipfs.dweb.link/

**Comment by dchoi27** [comment]
Hey there! You're getting this response regardless of what data you upload?

**Comment by mattlockyer** [comment]
I figured it out. I was seeing the top level object json not the underlying image object.

TBH it's pretty weird to have such an opinionated API like this. e.g. describing tokens.
