### ISSUE TITLE
Upload stopped working, getting 500 Internal Server Error

### ISSUE THREAD

**Issue by salgodev** [ipfs-shipyard/nft.storage#280]
Hi, it looks like the upload API is currently down. Getting 500 Internal Server Error with the following error response:

`
{
  "ok": false,
  "error": {
    "code": "SyntaxError",
    "message": "Unexpected end of JSON input"
  }
}
`

Any idea what's wrong?

Thanks!

**Comment by contra** [comment]
@salgodev Did you figure something out? We're having the same issue - started yesterday.

**Comment by mikeal** [comment]
Nah, that was a different issue. What we’re seeing now is something new.
