### ISSUE TITLE
Hi! Can you increase the limit pls (need 200mb)

### ISSUE THREAD

**Issue by putinogov151616** [ipfs-shipyard/nft.storage#281]

**Comment by nhlong2** [comment]
There is a way to get around the limit. You can not upload files bigger than 100MB, but you can pin files bigger than 100MB through its pinning service.
`ipfs pin remote service add nft-storage https://api.nft.storage YOUR_API_KEY`
[Docs](https://ipfs.github.io/pinning-services-api-spec/)
