### ISSUE TITLE
Getting Error 500 

### ISSUE THREAD

**Issue by vancedy** [ipfs-shipyard/nft.storage#283]
Using the test code in the NPM repository,

I'm gettting Error 500: Internal Server Error at the client.store call.
I tried logging the client, but I am just getting this: 

`NFTStorage {
  token: 'TOKEN HERE',
  endpoint: URL {
    href: 'https://api.nft.storage/',
    origin: 'https://api.nft.storage',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'api.nft.storage',
    hostname: 'api.nft.storage',
    port: '',
    pathname: '/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  }
}
`

**Comment by mikeal** [comment]
Thanks for reporting, we’re looking into it now.

**Comment by HomelyHyperion** [comment]
Yup, same here.

**Comment by yushenzaishi** [comment]
user node js Error: Unexpected end of JSON input

**Comment by HomelyHyperion** [comment]
> Thanks for reporting, we’re looking into it now.

![5iqto6](https://user-images.githubusercontent.com/16502719/128453894-bcf03b8b-58e9-4214-b41e-cc6a41b39a31.jpg)

**Comment by alanshaw** [comment]
There was an outage on Friday but it has now been resolved. Please shout if you're still experiencing issues.
