### ISSUE TITLE
Failed to upload data with api 

### ISSUE THREAD

**Issue by ZhangPeibin** [ipfs-shipyard/nft.storage#290]
We get this error:

"524: Origin Time-out"
[[Prototype]]: Object
ok: false
[[Prototype]]: Object

the file size : 82472056

**Comment by Xx-thoth-xX** [comment]
Also have been seeing this error as well, is that just due to server overload? It happens maybe 1  out of 20 uploads for me.

**Comment by Xx-thoth-xX** [comment]
524 is cloudflare specific:

Error 524: a timeout occurred
Error 524 indicates that Cloudflare successfully connected to the origin web server, but the origin did not provide an HTTP response before the default 100 second connection timed out.

Enterprise customers can increase the 524 timeout up to 600 seconds.
Resolution Contact your hosting provider to exclude the following common causes at your origin web server:

A long-running process on the origin web server.
An overloaded origin web server.

**Comment by alanshaw** [comment]
Heya, what file size are you uploading and which client method are you calling?

**Comment by ZhangPeibin** [comment]
@alanshaw the file size : 82472056 and I was use http request

**Comment by dchoi27** [comment]
Hey, could you try again and let us know whether this was resolved?

**Comment by ZhangPeibin** [comment]
I will try it and once I find the error , I will send it to you
