### ISSUE TITLE
Flaky upload issues

### ISSUE THREAD

**Issue by dave4506** [ipfs-shipyard/nft.storage#293]
We have been observing issues with storing file blobs with NFT.storage and can't pin point exactly why. It happens sporadically and throw an error in regards to the file blob (which are json files) not being formatted correctly. 

Any resolution to this?

**Comment by dchoi27** [comment]
Hi there - can you give some more detail? What do you mean by sporadic - do you always get errors from trying to store a given file, or do you experience different results each time you run? Any patterns to the files that you encounter this with?

**Comment by dchoi27** [comment]
Let us know if you are still facing issues!
