### ISSUE TITLE
Error: reason: "", details: "": 500 Internal Server Error  - Upload doesnt work

### ISSUE THREAD

**Issue by adriadrop** [ipfs-shipyard/nft.storage#297]
Been using NFT.STORAGE for weeks now as a place to pin my IPFS files but from few days ago when I try to pin files all I get is

Error: reason: "", details: "": 500 Internal Server Error

`ipfs pin remote add  --name=jsons --service=nft QmNtPwsigduomZmhQoyQKgLbL7m2E3m1DnNPyHWavxv5Up`

using pinata the same way and all works well. Something seems wrong with system

**Comment by adriadrop** [comment]
I am just using CLI so i dont have a way to choose, just errors out.

**Comment by dchoi27** [comment]
Please try again and reopen if not resolved!
