### ISSUE TITLE
Uploads not showing in "Files" UI

### ISSUE THREAD

**Issue by markcarey** [ipfs-shipyard/nft.storage#298]
When I click on "Files" in the top menu, I get a screen with a red banner, with a message "An unexpected error has occurred." in the main body of the page. The console has the following error: `Unhandled Promise Rejection: ReferenceError: Can't find variable: BigInt`.

When I then refresh the page, the header banner turns yellow/mustard and the main body has only the message "Files - NFT Storage.". No files are listed.  The `ReferenceError: Can't find variable: BigInt` is still in the console.

MacOS 10.15.7 / Safari 13.1.3

Example CID that should be there: `bafkreibdbvlg7hgvllhlzetwlehciiy4buykksox3qpyfcszmcxsifp7ka ` (confirmed successful via the `GET /{cid}` endpoint and via IPFS gateways.

Uploaded using the following JS:
```
fetch('https://api.nft.storage/upload', { 
                method: 'post', 
                headers: new Headers({
                    'Authorization': 'Bearer MY_API_TOKEN', 
                    'Content-Type': 'application/json'
                }), 
                body: JSON.stringify(jsonObj)
});
```

**Comment by markcarey** [comment]
Just tried this in Chrome, and the files are all showing. So this issue seems specific to Safari.

**Comment by dchoi27** [comment]
cc @hugomrdias FYI

**Comment by hugomrdias** [comment]
Hey @markcarey thank you for your feedback.

That version of safari doesnt support `BigInt`, only Safari 14+ has support for it. Unfortunately the only option right now is to upgrade safari or use another browser. 😞

Our current roadmap doesn’t include support for older browsers, if that changes i will let you know for now im gonna close this issue.

Thank you.

**Comment by markcarey** [comment]
I see Safari 14 is a pending upgrade on my machine. I recently upgraded my aging mid-2012 MBP to Catalina, so 14 wasn't an option until now. ;) I will do the upgrade and try it....
