### ISSUE TITLE
How to use nft.storage as a remote pinning service ? 

### ISSUE THREAD

**Issue by david-dacruz** [ipfs-shipyard/nft.storage#309]
Hello I am trying to figure out use nft.storage as a remote pinning service can someone share an example or can you provide more documentation please ? Thanks ahead!

**Comment by frehml** [comment]
This is a good guide to get started: https://www.youtube.com/watch?v=ZMv_-tC-uEc

**Comment by ebnth-zorea** [comment]
Is this method still supported? I notice docs on site removed it and API server is now "https://api.nft.storage" vs /api

**Comment by Moikapy** [comment]
I'm trying to use on the ipfs gui and it's failing to fetch
