### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by frehml** [ipfs-shipyard/nft.storage#310]
Getting a syntax error when uploading a large amount of files (50 or so), works when I upload a small amount of files (5 or so). Uploading is done via storeDirectory
```
undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
```

**Comment by alanshaw** [comment]
You might be coming up against the 100MB limit for single uploads. Eventually this will be built in to the client but for now you'll have to use the `storeCar` method and the `ipfs-car` module to pack your files.

There's an example here https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/examples/node.js/storeCar.js

**Comment by frehml** [comment]
Thanks for your reply, does the remote pinning service support 32GB uploads as mentioned on the website?

**Comment by alanshaw** [comment]
Yes, and also not sure if I was clear that using `storeCar` allows you to upload NFTs bigger than 100MB also.

**Comment by frehml** [comment]
I fit the code to my needs but getting an Origin Time-out now

```
async function uploadImages(){
  const client1 = new NFTStorage({ token: apiKey1 })
  for(const data of metadata){
    const id = data.edition.toString()
    const cid = await client1.storeBlob(new Blob([ await fs.promises.readFile('./output/images/' + id + ".png")], id, {type: "img/png"}))
    console.log(cid)
  }
}
```

Each image is definitely smaller than 100mb, is it because I'm calling the API too fast in succession? If this is not viable I will try and implement CAR (I don't really know how it works). Thanks for your help!

**Comment by frehml** [comment]
I reactored the code to work with `storeCar`, yet I'm still getting Error 524 Origin Time-out, same thing happening here a small amount of files works but a bigger amount doesn't (yet everything is under 100mb). Here is the code:

```
async function uploadImages(){
  const client1 = new NFTStorage({ token: apiKey1 })
  const client2 = new NFTStorage({ token: apiKey1 })

  const { root1 } = await packToFs({
    input: `${process.cwd()}/output/images`,
    output: `${process.cwd()}/output/car/images.car`,
  })

  const carReader1 = await CarIndexedReader.fromFile(
    `${process.cwd()}/output/car/images.car`,
  )
  
  const cid1 = await client1.storeCar(carReader1)

  for(const data of metadata){
    const id = data.edition.toString()
    data.image += cid1 + "/images/" + id + ".png"
    fs.writeFileSync('./output/metadata/'+id, JSON.stringify(data, null, 4));
  }

  const { root2 } = await packToFs({
    input: `${process.cwd()}/output/metadata`,
    output: `${process.cwd()}/output/car/metadata.car`,
  })

  const carReader2 = await CarIndexedReader.fromFile(
    `${process.cwd()}/output/car/metadata.car`,
  )

  const cid2 = await client2.storeCar(carReader2)
  console.log(cid2)
}
```

PS: using 1 client has the same effect

**Comment by alanshaw** [comment]
@frehml please could you have another try? 🙏 We think the issue is now resolved.

**Comment by dchoi27** [comment]
Please reopen if this is still an issue!

**Comment by dchoi27** [comment]
@rafinskipg have you tried using `storeCar()` like @alanshaw mentioned? Alternatively the PR to make the chunking automatic in the JS client should land early this week if you want to wait (#558)
