### ISSUE TITLE
Error: 524: Origin Time-out     at Function.storeDirectory

### ISSUE THREAD

**Issue by luffkaa** [ipfs-shipyard/nft.storage#311]
Hi!
Try to store folder with pack of small JSONs and getting this error:
```js
Error: 524: Origin Time-out
    at Function.storeDirectory (lib.js:173)
```

But, sometimes upload working fine (after few attempts).

I would be very grateful for any advice on how to solve this problem.

My function is:
```js
export async function uploadToNFTStorage(files: File[]) {
  const client = new NFTStorage({
    token: NFT_STORAGE_API_KEY
  });

  try {
    const cid = await client.storeDirectory(files)
    return cid
  } catch (err) {
    console.log(err)
    return err
  }
}

**Comment by alanshaw** [comment]
@luffkaa please could you have another try? 🙏 We think the issue is now resolved.

**Comment by luffkaa** [comment]
> @luffkaa please could you have another try? 🙏 We think the issue is now resolved.

Seems like it work good now. Thank you!
