### ISSUE TITLE
CLI Upload Hangs Forever

### ISSUE THREAD

**Issue by noam-alchemy** [ipfs-shipyard/nft.storage#312]
Trying to follow the guide the home page. Created an account and API key, and the following command hangs forever:

` curl -X POST --data-binary test.jpg -H 'Authorization: Bearer <key>' https://api.nft.storage/upload`

**Comment by dchoi27** [comment]
Can you try again and let us know if this has been resolved?

**Comment by dchoi27** [comment]
Please reopen if not resolved!
