### ISSUE TITLE
Exampels Directory url not working

### ISSUE THREAD

**Issue by skyttedk** [ipfs-shipyard/nft.storage#321]
The Url to the examples directory is not valid.

https://ipfs-shipyard.github.io/nft.storage/client/examples

**Comment by alanshaw** [comment]
Where did you find this link @skyttedk? Any chance you can send a PR to fix?

**Comment by dchoi27** [comment]
Closing for now, please let us know if you can point us where you saw the broken link!

**Comment by pichiste** [comment]
It's the "examples directory" link at the bottom of this page: https://ipfs-shipyard.github.io/nft.storage/client/

**Comment by dchoi27** [comment]
Thanks! This PR should address #403
