### ISSUE TITLE
toGatewayURL() returning Unhandled Rejection (TypeError): Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by adhiesg** [ipfs-shipyard/nft.storage#324]
hello. i'm trying to convert to ipfs:// link I got after storing data with toGatewayURL. I'm passing metadata.url as the parameter but it returns error. I'm currently learning and the documentation seems a little bit hard for me since there is no real example for the usage. this is the syntax I used 
![image](https://user-images.githubusercontent.com/28957135/129987894-e14e0688-1ea5-4141-be65-bccbe856bd0b.png)

**Comment by dchoi27** [comment]
Hey, I think you're passing in an object into `toGatewayURL` instead of a string https://ipfs-shipyard.github.io/nft.storage/client/modules.html#toGatewayURL Think just taking out the brackets in the parameters should do the trick?

**Comment by dchoi27** [comment]
Let me know if that wasn't the issue! Closing for now
