### ISSUE TITLE
Migrate niftysave to Postgres

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#328]
Task list

Roughly steps to get there:

- #378 
- #381
- #384
- #402 
- #520 
- #478 
- #477 
- #497 
- #521
- #504 
- #532

**Comment by JeffLowe** [comment]
Current status:  finishing up migration of remaining entities.

**Comment by Gozala** [comment]
Rough steps to get there

#378 
#381
