### ISSUE TITLE
how can i use the nft strorage's chunk feature?

### ISSUE THREAD

**Issue by yansenzu** [ipfs-shipyard/nft.storage#332]
i have an problem that i can't upload large file, so i read from nft strorage website that it can support chunk file, where i can found the docs for that?
thank you

**Comment by dchoi27** [comment]
How large is your file? There's a 32 GB limit. The chunking refers to getting files larger than 100 MB onto NFT.Storage.

**Comment by dchoi27** [comment]
#220 would also implement client-side chunking automagically in the library if you want to track that!

**Comment by dchoi27** [comment]
Closing for now, let us know if you'd like to pick the discussion back up!

**Comment by atarev-crypto** [comment]
What is the correct route to upload if you have created, and chunked (using carbites) your own CAR, in order that it's put together correctly under the CAR's CID? I have a large (8GB) CAR I have split into 99MB pieces, but using the HTTP method I get '413 Request Entity Too Large' still, and using the JS client examples don't seem to have a method that fits my use case. I just need a bunch of files uploaded in one IPFS directory (we are using DNSlink to point to the NFT content).

**Comment by dchoi27** [comment]
@alanshaw can correct me if I'm wrong tomorrow, but you just upload each CAR chunk using `upload` and the backend will restitch it all together under the same root CID.
