### ISSUE TITLE
documentation site is down

### ISSUE THREAD

**Issue by dantrevino** [ipfs-shipyard/nft.storage#333]
Linked from the nft.storage home page.

https://ipfs-shipyard.github.io/nft.storage/client/classes/lib.nftstorage.html

![image](https://user-images.githubusercontent.com/7738/130332068-d2e59605-89b9-49f7-8a6f-4a025cca483b.png)

**Comment by dchoi27** [comment]
Is that what a link from the homepage took you to? The link at the bottom here
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/982110db-118b-4264-a042-04d374e9fcba)
took me to this URL (which is different and works for me): https://ipfs-shipyard.github.io/nft.storage/client/

**Comment by dantrevino** [comment]
Yes that's the link. It's working for me now as well.
