### ISSUE TITLE
ipnft documentation

### ISSUE THREAD

**Issue by dantrevino** [ipfs-shipyard/nft.storage#349]
Is there documentation on `ipnft` somewhere?  STFW only useful link is  a Molecule biopharma medium article.  Also is there an nft.storage discord somewhere?

**Comment by dchoi27** [comment]
Hey, you can join the nft.storage Discord channel here: https://discord.gg/xbrHbnnJ Also can join via Filecoin Slack (#nft-storage channel) if you have an account there

Where did you hear about `ipnft`? It seems like there's two NFT-related things it refers to: InterPlanetary NFT Extensions (which @Gozala has put down some thoughts for [here](https://github.com/Gozala/ipnft)), and the Molecule Medium article you mention (where IP looks to stand for intellectual property and seems unrelated). The nft.storage product is separate from either effort.

**Comment by dantrevino** [comment]
I heard about `ipnft` from the source code.  There are references to it everywhere.  For instance:  https://github.com/ipfs-shipyard/nft.storage/blob/6f6fc249ac4bcfe6905fceed8b767774f4dc38ea/packages/api/test/nfts-store.spec.js#L74.

Thank you for the pointer to @Gozala's notes and the discord.

**Comment by Gozala** [comment]
@dantrevino I'm afraid @dchoi27's pointer is incorrect, we can blame @mikeal for suggesting to use the same `ipnft` acronym for two different things 😳

@dantrevino I'll assign this issue to myself as an action item to spec what the IPNFT in the context of nft.storage, below is a TLDR:

1. NFTs often refer to multiple resources / assets not just one that is specified in `image` field of `metadata.json`. 
2. To include ipfs:// links to a resources/assets  in `metadata.json` first one needs to add them to the IPFS network (to get a CID). And only after it is possible to generate `metadata.json` with corresponding links. This creates a multistep process.

To simplify the flow here and follow the [best practices by default](https://blog.ipfs.io/2021-04-05-storing-nfts-on-ipfs/) nft.storage client exposes [`client.store`](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#store) API which takes a JSON object you'd want to store as `metadata.json`, except it can contain `Blob` / `File` fields. Given such an object we:

1. Pin all the files / blobs in it.
2. Replace those files / blobs with `ipfs://` style urls (in string representation) and
3. Pin it as `metadata.json`
4. Create an [IPLD]https://ipld.io) DAG that contains same data as input object, except files / blobs are swapped with IPLD Links to corresponding files in IPFS and link to metadata.json.

Here is an example of such a dag [bafyreifn4ctfna4mh2yrbvjacqrxtqv45c3t34rdd4djwsc4x475znyyia](https://explore.ipld.io/#/explore/bafyreifn4ctfna4mh2yrbvjacqrxtqv45c3t34rdd4djwsc4x475znyyia) you can see it's encoded as [DAG-CBOR](https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md) has all the same data as metadata.json and links to all the resources. Here is also link to an [example that I've used to make it](https://observablehq.com/@protocol/example-for-349).

We end up including CID to such dags in the `ipnft` property of the return object of `store` API.
