### ISSUE TITLE
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' 

### ISSUE THREAD

**Issue by luizoamorim** [ipfs-shipyard/nft.storage#357]
I'm using nft.storage in my project. This library have ipld dependence.

I've got this error when I try generate a project build:

./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').

Can somebody help me?

**Comment by dchoi27** [comment]
Hey, take a look at #215 and see if anything there helps. Otherwise, we need more detail to help reproduce (code, etc.). Thanks!

**Comment by dchoi27** [comment]
Closing for now - feel free to reopen if needed.
