### ISSUE TITLE
Opensea struggling to read .json file extension

### ISSUE THREAD

**Issue by DigitalMarketing4Leads** [ipfs-shipyard/nft.storage#359]
Heya, I am struggling to get OpenSea to reliably read the metadata from the .json file when it has the .json file extension. Is there a way to remove the .json from the file?

E.g. /metadata instead of /metadata.json?

**Comment by alanshaw** [comment]
Do you have some more context on this? In what way is it struggling? Are you getting an error?

**Comment by DigitalMarketing4Leads** [comment]
Hi, thanks for the response. I want to say upfront that I am very new to this and have been learning a lot in the last week, so it is possible that my observations are incorrect.

I have been testing deploying ERC721 tokens through a smart contract and then viewing them on opensea. Before I found nft.storage, I was using the baseUri approach and putting the metadata in an ipfs folder and then manually uploading the metadata files as 0, 1, 2, 3. These files cannot be names 0.json, 1.json, etc as Opensea will not validate them and display the metadata.

I found the same thing for the contractUri which again worked flawlessly when I removed the file extension and reuploaded.

I wanted a way to create the metadata during the minting process - image creation, metadata creation, mint token. All in one function.

I have successfully created a new image, added it to the .json files and assigned these to the tokenUri of the token. The tokenUri is correct when I read the contract on rinkebey etherscan. However, OpenSea does not pull through the metadata correctly.

It worked perfectly for one token, it pulled through the name/description and not image for another and then it didn't work at all for the third.

I suspect that the problem lies in the json file.

+ I could be inputting the code incorrectly and there might be a mistake in the metadata file (I have checked this and I don't think so)
+ The file extension could be the problem (i.e. it might work better as just filename ipfs/hash/metadata rather than ipfs/hash/metadata.json


I have tried updating the metadata on OpenSea but it does not work.

Here is an example:

https://testnets.opensea.io/assets/0x4fa468a678b2cb7e5b9032d00637782cc2096c85/1

This token has the name and description from metadata, but no image.

tokenURI - ipfs://bafyreihp4lwq74jfn72l64tt657t34gob7gkb5jqypafudpdcscqaqhnvm/metadata.json

In chrome it shows:

{
name: "TeFi #00002",
description: "Removed contractURI - hoping that this stops the unwanted image loading. Removed attributes.",
image: "ipfs://bafybeifadzahhhpfdvzgscrsdoqwoeprbefu2ao5cs4eo3uzgjgpukptv4/TeFiimage.png"
}

in brave it shows:

{"name":"TeFi #00002","description":"Removed contractURI - hoping that this stops the unwanted image loading. Removed attributes.","image":"ipfs://bafybeifadzahhhpfdvzgscrsdoqwoeprbefu2ao5cs4eo3uzgjgpukptv4/TeFiimage.png"}

The image exists.

=

The token is validated by OpenSea:

https://rinkeby-api.opensea.io/asset/0x4fa468a678b2cb7e5b9032d00637782cc2096c85/1/validate


= 

Any ideas why the image is not showing on OpenSea would be really helpful.

=

**Comment by dchoi27** [comment]
Hey, so this is likely something on the OpenSea side. If they're reading some elements of your metadata, then they're reading your metadata. I think the issue is probably on how they render the image - I know they pull the image from the ipfs.io HTTP gateway, which has been having some issues with being under heavy loads lately. I would confirm with them that this is the case, but a separate team is working with them to improve that gateway's reliability. Our team is also looking into this as well to help out.

**Comment by DigitalMarketing4Leads** [comment]
I have been trialing hosting images on ipfs (desktop app), nft.storage and pinata and the way that the URL is structured on pinata seems to get read much better. Whenever I have created metadata to this test image, it has always worked on this URI:

https://gateway.pinata.cloud/ipfs/QmP9xhaG2a2voc6ye8NWPrGHaXKsvDgy8ELpPZKg4nv5Ft

I'm really keen to generate the metadata and images during the minting process for the project I'm working on. Last year was really tough for me and an organisation really helped me out. I'm hoping that this project will raise funds for them and it is important for me to see it through to completion.

Have you got any other suggestions or do you know of any dev's with some time that I could reach out to help? We have secured funding and looking to move fast.

**Comment by dchoi27** [comment]
Hey, as mentioned I think this is mostly on the OpenSea side. The fact that the metadata works when accessed via a different HTTP gateway (Pinata's) makes me think it relates to some recent trouble with the ipfs.io gateway, which OpenSea uses to pull data from the IPFS network and cache it on their side (so if something went wrong on this first pull, the caching could have been messed up - this is just an educated guess though and they might know better). A lot of those problems are better now, so maybe try minting a new NFT again, and if it still doesn't work, then might reach out to them!

I'll close on our side for now, but feel free to ask more questions like this in the IPFS Discord (https://docs.ipfs.io/community/chat/#discord) where more people might be helpful!

**Comment by iamcoderave** [comment]
Heya all, just wanted to give an update. It turns out that it was something external. The metadata has now all rendered perfectly. Thank you for your awesome support and advice.
