### ISSUE TITLE
Add Countly to NFT.Storage website

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#360]

**Comment by alanshaw** [comment]
@dchoi27 can you help define what would be useful to track on the nft.storage website? 🙏 

For example, the same PR on web3.storage: https://github.com/web3-storage/web3.storage/pull/126

**Comment by dchoi27** [comment]
@zebateira basically the same as in web3.storage:
-  Track page views
-  Track 404s
-  Track header and footer links
-  Track other links to docs and other pages
-  Track CTA clicks and other actions
-  Login / Logout
-  Files (Upload / Delete)
-  Tokens (Create / Copy / Delete)
