### ISSUE TITLE
Add hamburger to NFT.Storage website

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#361]
@alanshaw - is this just for mobile?

**Comment by alanshaw** [comment]
Yes, just for mobile. Looks like this currently:

![Screen Shot 2021-09-01 at 15 35 42](https://user-images.githubusercontent.com/152863/131700226-53240ed6-2b4f-4a77-8a46-91ad87dde01d.png)

![Screen Shot 2021-09-01 at 15 35 19](https://user-images.githubusercontent.com/152863/131700273-412723a3-2367-4b38-82ad-ab171ebdf80e.png)
