### ISSUE TITLE
Fix diagram on homepage

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#363]
From @alanshaw: Metadata.json file is not ERC-721 format

**Comment by alanshaw** [comment]
<img width="365" alt="Screenshot 2021-09-01 at 15 38 21" src="https://user-images.githubusercontent.com/152863/131700580-bfab5517-9cfa-42f6-b831-3d44f7ee08df.png">

Basically the "properties" object in the image above should be what is shown. Not the rest!
