### ISSUE TITLE
Remove Beta tag from the site

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#365]

**Comment by dchoi27** [comment]
@jdiogopeixoto can you check if it removes BETA from the preview? https://github.com/ipfs-shipyard/nft.storage/pull/397#issuecomment-915306464

**Comment by jdiogopeixoto** [comment]
It doesn't, I wasn't sure if that BETA was referring to something else so I didn't remove it. I will remove it now. Thank you!
