### ISSUE TITLE
Remove remote pinning service docs from the site

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#366]
@alanshaw where are these?

**Comment by alanshaw** [comment]
We've seen a lot of abuse so we're going to stop advertising their presence (although not remove them).

https://nft.storage/#configure-as-a-remote-pinning-service

**Comment by dchoi27** [comment]
Cool. What do you mean by stop advertising but not remove them? We want to remove the right box but keep the ability to use it as a pinning service?

**Comment by arpu** [comment]
any more infos on this? would love the pinning service for some new genrated NFTs
