### ISSUE TITLE
can not login into the NFT.Storage

### ISSUE THREAD

**Issue by anxiaoxiong** [ipfs-shipyard/nft.storage#367]
I input my email,and recevice the login-email. but,when i clicked the login button. i am redirected to the homepage,but still let me login.  
my email is happybearing@liev.cn
i tried more times. return the same result

**Comment by anxiaoxiong** [comment]
i had try Google Chrome and Firefox .  @hugomrdias

**Comment by dchoi27** [comment]
That's odd that it happens to you in multiple browsers. Does the Github authentication link work? Can you share browser logs?

**Comment by dchoi27** [comment]
Closing for now - feel free to reopen if needed.
