### ISSUE TITLE
Unable to parse data using File or Blob

### ISSUE THREAD

**Issue by ltfschoen** [ipfs-shipyard/nft.storage#37]
In this PR https://github.com/near-apps/nft-launcher/pull/1 I tried different ways to deploy either plain text, a static image, and an animated gif to NFT Storage so we could retrieve it and use it with NEAR Protocol but unfortunately I couldn't get `Blob` or `File` to parse any of the data provided to it, whether it was given plain text, base64 string, or a filename.

**Comment by alanshaw** [comment]
I've commented on the PR. Please re-open if you're still not able to get it working 😁🤞
