### ISSUE TITLE
Rewire niftysave Cron jobs to new Postgres.

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/nft.storage#384]
Once we have completed #381 we should rewire CRON jobs to a new database. This would also involve implementing corresponding GraphQL endpoints or alternative mechanisms to read / write data.

**Comment by dchoi27** [comment]
@Gozala can this be closed?

**Comment by dchoi27** [comment]
nvm - see PR #504

**Comment by the-simian** [comment]
This is in progress on a few PRS
#517 
#503 -> #505 (503 was merged into 505)
