### ISSUE TITLE
Getting Cross-Origin Request Blocked on API call

### ISSUE THREAD

**Issue by anon-br** [ipfs-shipyard/nft.storage#393]
I'm trying to upload a .png file through the `https://api.nft.storage/upload` endpoint from my local machine and getting CORS' s Cross-Origin Request Blocked error.

The exactly same call from https://nft.storage/api-docs/ works nicely.

```
return fetch("https://api.nft.storage/upload", {
  method: 'POST',
  headers: {
      'accept': 'application/json',
      'Content-Type': 'image/*',
      'Authorization': 'Bearer MY_API_KEY', // removed apikey before post here
  },
  body: file, // using file here, but already tried using form and got the same error
})
```

![Screenshot 2021-09-03 14 38 40](https://user-images.githubusercontent.com/87387688/132046036-91804d2c-dd45-4896-9188-675c005943d2.png)

**Comment by dchoi27** [comment]
Hey there, just to get clarity, when you say "The exactly same call from https://nft.storage/api-docs/ works nicely," what are you referring to that's different than using `https://api.nft.storage/upload`?
