### ISSUE TITLE
Examples link is broken

### ISSUE THREAD

**Issue by avaer** [ipfs-shipyard/nft.storage#411]
https://ipfs-shipyard.github.io/nft.storage/client/ -> https://ipfs-shipyard.github.io/nft.storage/client/examples ->

![image](https://user-images.githubusercontent.com/6926057/132877065-839e3e48-0000-42af-adbc-035f3058ada6.png)

**Comment by dchoi27** [comment]
Thanks! Will be fixed when #403 is deployed. In the meantime this is the link: https://github.com/ipfs-shipyard/nft.storage/tree/2bb82aeb23ac139513c1af6615d010579f22a7cc/packages/client/examples
