### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by montanaflynn** [ipfs-shipyard/nft.storage#413]
Trying to upload a car file returns this error:

```
curl -X POST --data-binary @example.car -H 'Authorization: Bearer API_KEY' https://api.nft.storage/upload

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

From the FAQ this shouldn't happen:

Are there any size restrictions for stored NFTs?
NFT.storage can store NFTs up to 32GB in size! (There was previously a 100MB limit due to Cloudflare workers but NFT.storage now supports chunked uploads, allowing files bigger than 100MB to be uploaded! 🎉)

**Comment by dchoi27** [comment]
Ah, so I think we probably need to make that clearer in the FAQ, thanks for flagging. I think the <100MB chunking applies before files are CAR'd up. @alanshaw can share how you can generate a CAR using parameters that will work with NFT.Storage, or correct me if I'm wrong.

**Comment by alanshaw** [comment]
Heya, every request sent to `https://api.nft.storage/upload` has a 100MB limit. So sending a CAR file on it's own won't help with the limit.

However, CAR files can be split into multiple parts and can be sent in multiple requests. The [`storeCar`](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#storeCar) method of the JS API will do this for you automatically. It splits each CAR file into 10MB chunks and sends up to 3 requests concurrently.

You can do the same using curl, but you need to split your big CAR up first, and then send each chunk. There's a CLI tool you can use to split up a CAR file here: https://github.com/nftstorage/carbites-cli/

Note: you'll need to use the `treewalk` strategy e.g.

```console
carbites split example.car --size 10MB --strategy treewalk
```

**Comment by dchoi27** [comment]
Closing for now - let us know if this doesn't answer things!
