### ISSUE TITLE
How to upload a car file

### ISSUE THREAD

**Issue by azpublic** [ipfs-shipyard/nft.storage#415]
Hi ! thanks for the great project. 

I'm looking for a way to upload thousands of images under the same IPFS directory. 

the idea is to be able to access the files using the same root URL as such : 

ipfs://XXXXXXXX/1  --> metadata
ipfs://XXXXXXXX/1.png
ipfs://XXXXXXXX/2  --> metadata
ipfs://XXXXXXXX/2.png
ipfs://XXXXXXXX/3  --> metadata
ipfs://XXXXXXXX/3.png
 
etc .. 

By browsing the issues in here some user suggested to create a CAR file by using https://car.ipfs.io/. 
I tried to upload that car file using NFTStorage.storeCar following the example available at https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#storeCar 

but without success. 

The idea is to combine NFT.storage with openzeppelin's ERC721  tokenURI( tokenId ) method which concatenates a base URI with a token ID number. 

What is the correct way to achieve what I'm trying to do . 

Thanks for any help.

**Comment by dchoi27** [comment]
Hey! Can you share what error messages you're getting and any other relevant details?

**Comment by azpublic** [comment]
Hi, 
I Finally managed to upload a CAR file using CarReader with a filestream. I can see the root folder of the car file whenever I visit the ipfs.dweb.link url but when I try to enter that folder I get : 

internalWebError: context canceled

**Comment by dchoi27** [comment]
Hey, can you share the CID?

**Comment by dchoi27** [comment]
Hey there - closing for now! Let us know if the problem persists.
