### ISSUE TITLE
 context deadline exceeded

### ISSUE THREAD

**Issue by azpublic** [ipfs-shipyard/nft.storage#419]
Hi ! 

I'm unable to view a recently uploaded file ( uploaded through js library ) when trying to access it through the gateway at http://dweb.link/ipfs/XXXMYCIDXXX/87.jpg : 

getting the following message in the browser
ipfs resolve -r /ipfs/XXXMYCIDXXX/87.jpg: context deadline exceeded

although I was able to access the corresponding metadata.json a bit before trying to access the image directly. 

Thanks for any help.

**Comment by alanshaw** [comment]
If you can provide the CID I can look into it 😄

**Comment by dchoi27** [comment]
Hey there - let us know if the problem persists, and if so, please do share the CID. thanks!
