### ISSUE TITLE
Additional details on homepage around availability of content

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#424]
We've gotten a lot of questions regarding availability of content, especially from folks wondering if they should be pinning content themselves or availability of gateways (which makes sense, given some of the scaling issues of the ipfs.io gateway scaling that were recently mitigated).

On our homepage, we can clarify things in a few places.

We can add some text around pinning content to your own node + a link on how to do so here (mentioning that this helps guarantee availability of content even if nft.storage is down):
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/67beb9da-749d-4f8a-be08-df71a5093b16)

We can add some color around the gateway option here (mentioning that gateways allow folks to access your content over HTTP, but it's dependent on the gateway availability - though luckily if one gateway is down, there are others you can use):
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/2767019a-13b3-4a02-aabb-96e24202ac1f)

We can also add an FAQ at the bottom explaining how gateways work.

**Comment by jdiogopeixoto** [comment]
@dchoi27 can you specify what text/links do we want to add?

**Comment by dchoi27** [comment]
@yusefnapora can you verify this link is the best one to help users pin content to their own nodes: https://docs.ipfs.io/concepts/persistence/#pinning-in-context

If so, we can add to `Store`:
```
Optionally, you can provide additional redundancy by running your own IPFS node and [pinning](https://docs.ipfs.io/concepts/persistence/#pinning-in-context) the CIDs of content uploaded to NFT.Storage. Alternately, you can use an [additional pinning service](https://docs.ipfs.io/concepts/persistence/#pinning-services) for redundancy (NFT.Storage already does this when it backs things up to Pinata). Doing this is not necessary, but might be of interest for users looking to be in full control of their data and its availability.
```

For `Retrieve`, let's add a paragraph with:
```
If fetching content using a public IPFS gateway (e.g., directly using an HTTP URL or via Brave), note that the availability and speed of retrieving the content depends on the gateway. In cases where the gateway is unable to retrieve a given CID (e.g., returns a 429 error), you can try a different gateway or running and using your own IPFS node instead.
```

In the FAQ, we can add:
```
Q: I tried using an HTTP gateway to retrieve my content from IPFS but am receiving an HTTP error. Does this mean my content was not stored successfully on NFT.Storage?
A: Not necessarily! HTTP gateways are a great way for users who aren't running their own IPFS nodes to retrieve content from the IPFS network. However, they do introduce a centralized point of failure to a user flow. If a given gateway is down, or is under too much load, or is facing other issues, users who are accessing content through that gateway might be unable to access content. In this case, we recommend trying another gateway or running and using your own IPFS node.
```

Can you add @yusefnapora and me as reviewers on the PR? Thanks!
