### ISSUE TITLE
More docs for using NFT.storage at scale

### ISSUE THREAD

**Issue by mishmosh** [ipfs-shipyard/nft.storage#426]
I am seeing an increasing interest in people using or evaluating NFT for production usage. They have questions that are not well-answered by the "getting started" material currently published.

Rather than answering 1 at a time, I think a broader "using NFT.storage at scale" or "designing your application with NFT.storage" piece would be very timely and useful.

Let's use this thread to track all the questions/considerations coming up in this area. Then maybe we can set up a chat with team and turn it into a written longform piece for docs and/or blog.

**1. Minting & working with 100s of NFTs**
- I'm setting up a NFT Minter for the first time. I'm using the IPFS GUI. I need to pin 100 images and copy all CID hashes. Is there a way to easily Pin all to Pinata and export all CIDs? I'm currently doing each one by hand.

**2. Uploading 10000 NFTs and their metadata**
- Is the data pinned forever?
- What uptime guarantees are available?
- How many copies and which nodes are used?

**3. How permanent is my data?**

**4. Gateways and throughput**

**Comment by dchoi27** [comment]
Thanks! Agreed that there's a hole in the docs around how you think about building a service on top of NFT.Storage. Just to better understand who you the target audience you're hearing from is, is it developers thinking of making their own minting service?

cc @yusefnapora

**Comment by mishmosh** [comment]
One more in Slack recently: https://filecoinproject.slack.com/archives/C021JJRH26B/p1631889188141800

> Hi Team, is there a way to use storeDirectory with a for loop inside to list thousands of files in a folder?
```
hey! thanks Alan for your reply!! this is the code I was working on, but with no much success (probably as you said I might have to move to CAR way):
const {NFTStorage, File} = require('nft.storage')
const fs = require('fs')
require('dotenv').config()
const token = process.env.NFTSTORAGE_API_KEY
const imagesDir = '../metadata'
let metadataFiles = fs.readdirSync(imagesDir);
async function main () {
 const client = new NFTStorage({ token })
 const cid = await client.storeDirectory([
   //new File([await fs.promises.readFile(../metadata/1.json)], '1.json'),
   //new File([await fs.promises.readFile(../metadata/2.json)], '2.json'),
   for ( let i = 1; i <= metadataFiles.length ; i++ ){
     new File([await fs.promises.readFile(../metadata/${i}.json)], ${i}.json)
   }
 ])
 console.log(cid)
 const status = await client.status(cid)
 console.log(status)
 console.log(https://${cid}.ipfs.dweb.link)
}
main()
10:33
but that for loop is not working as I would expect it
```

response from alanshaw (could be massaged into docs example)
```const { NFTStorage, File } = require('nft.storage')
const fs = require('fs')
require('dotenv').config()

const token = process.env.NFTSTORAGE_API_KEY
const imagesDir = '../metadata'

async function main () {
  const metadataFiles = fs.readdirSync(imagesDir)
  const client = new NFTStorage({ token })
  const files = []
  for (let i = 1; i <= metadataFiles.length; i++) {
    files.push(new File([await fs.promises.readFile(`../metadata/${i}.json`)], `${i}.json`))
  }
  const cid = await client.storeDirectory(files)
  console.log(cid)
  const status = await client.status(cid)
  console.log(status)
  console.log(`https://${cid}.ipfs.dweb.link`)
}
main()

10:42 try that?
10:43 If the total size of all the files is more than 100MB then you'll need to upload a CAR.
```

**Comment by dchoi27** [comment]
Addressing these in NFT School here! https://github.com/protocol/nft-website/issues/138
