### ISSUE TITLE
examples directory is 404

### ISSUE THREAD

**Issue by playerone2000** [ipfs-shipyard/nft.storage#427]
Hi,

The link to the examples directory is 404:  https://ipfs-shipyard.github.io/nft.storage/client/examples

**Comment by dchoi27** [comment]
Will be fixed once #403 is deployed! In the meantime this is the link: https://github.com/ipfs-shipyard/nft.storage/tree/2bb82aeb23ac139513c1af6615d010579f22a7cc/packages/client/examples
