### ISSUE TITLE
CAR files won't upload

### ISSUE THREAD

**Issue by jshstw** [ipfs-shipyard/nft.storage#434]
Keep trying to upload a new CAR file, however whenever I do so the button is stuck on "Uploading..." until it eventually gives up and goes back to the files page.

**Comment by 70nyIT** [comment]
same here. 48 hours ago everything was working fine. Now if I have a very small CAR file (300kb) it does. As soon as it gets up to 2MB, it doesn't upload anymore.

**Comment by fedecastelli** [comment]
same issue here! ☝️

**Comment by olizilla** [comment]
I've just tested a 3MiB CAR file and i'm able to upload it via the website. Are you still experiencing the issue? if you retry does it keep failing for you? Are you be able to share the CAR files you're trying to upload that aren't working?

**Comment by alanshaw** [comment]
Do you have an error message in the browser console or from the JS library you can share?

**Comment by jshstw** [comment]
Failed to load resource: the server responded with a status of 500 ()

Error: 524: Origin Time-out
    at Function.storeBlob (lib.js:100)
    at async t._fn (index.js:50)

**Comment by 70nyIT** [comment]
same for me

**Comment by olizilla** [comment]
Do you hit an error with non-car file upload as well? We're investigating, and any context you can share that might give us a clue is helpful!

**Comment by jshstw** [comment]
That's the thing. It's not all CAR files. I've successfully uploaded a few but this one won't. It's only 4mb and I've successfully uploaded larger ones since.

**Comment by olizilla** [comment]
How are you creating your CAR files? Are you able to share the one that isn't uploading?

**Comment by jshstw** [comment]
I'm using car.ipfs.io to create the CAR files. I cannot unfortunately as it's commissioned work

**Comment by 70nyIT** [comment]
personally, I never tried to upload a file directly before, I always did through CAR:
I tried now via script, and I get this error

```
(node:43990) UnhandledPromiseRejectionWarning: Error: Expected response with two entries, but got 6 instead
    at Function.store (.../node_modules/nft.storage/src/lib.js:202:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (.../nft-upload.js:27:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43990) [DEP0018] 
```

But I don't know if it's an error on my side. I don't think so, as I literally copy-pasted the example on your website.

**Comment by 70nyIT** [comment]
If I upload a file directly from your website, it works (while a CAR file keeps giving me error)

**Comment by olizilla** [comment]
@70nyIT can you share your script as a github gist or similar?

**Comment by olizilla** [comment]
@70nyIT that error suggests that you're hitting the /store endpoint which is does not handle CAR files. Only the /upload enpoint can take CARs. This is likely a sperate issue to the one that @jshstw is hitting.

**Comment by Gozala** [comment]
@70nyIT looks like you're using [`client.store` API](https://ipfs-shipyard.github.io/nft.storage/client/classes/NFTStorage.html#store) which takes very specific type of input. I'm suspecting there is an issue there, do you mind providing a code sample so it's easier to provide feedback.

**Comment by jshstw** [comment]
@olizilla Any ideas on what could be causing my issue?

**Comment by 70nyIT** [comment]
So, what I still getting the error, both on website and via script, is upload a CAR file. That I'm sure it's working as I've been using it successfully in the previous days. Here's a snippet

```
  const inStreamImgs = fs.createReadStream(`./imgs_output.car`)
  const readerImgs = await CarReader.fromIterable(inStreamImgs);
  const cidImgs = await client.storeCar(readerImgs);
```

Instead I tried to directly upload a .gif file as asked by @olizilla with the below script and it's not working, but that's outside of my request (while instead from your website UI perfectly works)

```
  const client = new NFTStorage({ token: apiKey })

  const metadata = await client.store({
    name: 'Pinpie',
    description: 'Pin is not delicious beef!',
    image: new File([/* data */], `./imgs/heavy.gif`, { type: 'image/jpg' })
  })
  console.log(metadata.url);
```

**Comment by Gozala** [comment]
> Instead I tried to directly upload a .gif file as asked by @olizilla with the below script and it's not working, but that's outside of my request (while instead from your website UI perfectly works)
> 
> ```
>   const client = new NFTStorage({ token: apiKey })
> 
>   const metadata = await client.store({
>     name: 'Pinpie',
>     description: 'Pin is not delicious beef!',
>     image: new File([/* data */], `./imgs/heavy.gif`, { type: 'image/jpg' })
>   })
>   console.log(metadata.url);
> ```

Are you saying this does not work ? If so could you please provide some details:

1. what error do you see
2. maybe upload a file itself so we can reproduce

**Comment by Gozala** [comment]
Looking at it I'm realizing that  file name `./imgs/heavy.gif` may indeed cause some issues. Code here assumes that we'll be getting two cids one for file and another for the wrapping directory:

https://github.com/ipfs-shipyard/nft.storage/blob/60499653c4ebb4ad4590527243a09bc8bb73c540/packages/api/src/cluster.js#L57-L66

I suspect that in this case we actually do get 3 CIDs though one for file, one for `imgs` dir and one for wrapping directory which would explain the error message

**Comment by Gozala** [comment]
> 

So, where I am still getting the error, both on website and via script, is uploading a CAR file. My script in that case I'm sure it's working as I've been using it successfully in the previous days. Here's a snippet

  ```js
  const inStreamImgs = fs.createReadStream(`./imgs_output.car`)
  const readerImgs = await CarReader.fromIterable(inStreamImgs);
  const cidImgs = await client.storeCar(readerImgs);
  ```

I would expect this to work, what kind of error are you seeing here ? Better yet would be an observable example illustrating an issue so it's possible to reproduce it.

**Comment by 70nyIT** [comment]
Better if we focus only on the CAR file error, forget about single file. That's not where I found the error.

Have you tried uploading a CAR file from your website UI? It doesn't work and returns a 5xx error.
Same from command line and the error I'm getting is the one I reported also above:

```
(node:43990) UnhandledPromiseRejectionWarning: Error: Expected response with two entries, but got 6 instead
    at Function.store (.../node_modules/nft.storage/src/lib.js:202:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (.../nft-upload.js:27:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43990) [DEP0018] 
```

Situation:

* I have a CAR file made with 2k very small files. The total size of the CAR file is around 2MB
* CAR file is fine as with other IPFS provider I can upload, and see it
* if I try to upload it, both via webUI or via command line (see above), I get the above reported error

Hope this helps to clarify everything

**Comment by Gozala** [comment]
@70nyIT so if we look at your code snippet (below) you are calling `client.storeCar` method, which should work

```js
const inStreamImgs = fs.createReadStream(`./imgs_output.car`)
const readerImgs = await CarReader.fromIterable(inStreamImgs);
const cidImgs = await client.storeCar(readerImgs);
```

however if we look at the error you're providing we see that you're calling `.store` function (see 2nd line):

```
(node:43990) UnhandledPromiseRejectionWarning: Error: Expected response with two entries, but got 6 instead
    at Function.store (.../node_modules/nft.storage/src/lib.js:202:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (.../nft-upload.js:27:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43990) [DEP0018] 
```

This leads me to believe that you either:

1. Not running the code you think you're running
2. The error you see is coming from somewhere else
3. Somehow client libary you're using is corrupt (maybe caused by some tooling)

Could please provide reproducible code snippet so we can try to debug this ? Or at least please provide the car file, otherwise I do not know how else can we make progress here.

**Comment by 70nyIT** [comment]
See, talking about two things made me missing up stuff....

The error I'm getting is a timeout error (`Error: 524: Origin Time-out`), that's the one reported by @jshstw in his second message. I have edited my previous message, so now it's correct. Sorry @Gozala for the confusion!

**Comment by 70nyIT** [comment]
Any news on this @Gozala ? No pressure, just if you can share with us how long you think this may take to you and your team to fix it. If one day, one week or one month 😊

**Comment by alanshaw** [comment]
Can you share with us a problematic CAR file?

**Comment by 70nyIT** [comment]
Sure, there you have it!
[json_to_upload_output.zip](https://github.com/ipfs-shipyard/nft.storage/files/7194580/json_to_upload_output.zip)

**Comment by alanshaw** [comment]
Thanks, looking into it now.

**Comment by alanshaw** [comment]
In this particular case, it is taking 4 minutes to import into IPFS, which is significantly longer than the service is willing to wait for uploads. We're still investigating.

**Comment by alanshaw** [comment]
@70nyIT we made some configuration changes and I was able to upload your file - are you able to verify?

**Comment by olizilla** [comment]
@jshstw @fedecastelli @70nyIT we think this is fixed, please let us know if you're still having the same issue.

**Comment by Nanaber** [comment]
Hi, I am having similar problem to that but my error is different. It says: Array buffer allocation failed. I am trying to upload car file 2.75 GB of nft assets. Can you please help me?

**Comment by Gioxxy** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/27723588/160940014-afe33eee-b0a4-4442-967d-e49275895761.png">
With 5Mb of CAR file and 25GB of nft assets. Now is > 110 000%

**Comment by mbledkowski** [comment]
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/27723588/160940014-afe33eee-b0a4-4442-967d-e49275895761.png">
> With 5Mb of CAR file and 25GB of nft assets. Now is > 110 000%

Your file has been uploaded over 110 times probably XD Now it is pinned by 110 servers or something
