### ISSUE TITLE
Add links to examples on docs section on homepage

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#439]
Right now it's not super obvious where folks can go for more examples for using NFT.Storage. Let's add them to the homepage. These are the ones I know of:
- For HTTP API, examples in [Github](https://github.com/ipfs-shipyard/nft.storage/tree/2bb82aeb23ac139513c1af6615d010579f22a7cc/packages/client/examples/browser)
- For JS Library, examples in [Github](https://github.com/ipfs-shipyard/nft.storage/tree/2bb82aeb23ac139513c1af6615d010579f22a7cc/packages/client/examples/node.js) and [NFT School](https://nftschool.dev/tutorial/end-to-end-experience/)

Can we add a sentence to the docs block for each to include links to these examples? 
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/45d0bfe6-4a9a-46cd-b84a-bdd888bba5f2)

Something like: "For additional example code, check out our [Github repo](https://github.com/ipfs-shipyard/nft.storage/tree/2bb82aeb23ac139513c1af6615d010579f22a7cc/packages/client/examples/node.js) and [NFT School](https://nftschool.dev/tutorial/end-to-end-experience/)."

@yusefnapora do you mind validating that these are the right examples to include?

**Comment by yusefnapora** [comment]
I think HTTP API example you linked also uses the JS client, just in a browser context instead of node. I'm not sure if we have a good example of using the HTTP API directly.

I think the links to the github repo and NFT School are good though 👍
