### ISSUE TITLE
Error: Memory limit would be exceeded before EOF

### ISSUE THREAD

**Issue by 0xSzeth** [ipfs-shipyard/nft.storage#445]
Hello,

I'm currently experiencing an issue while uploading NFTs > 300MB in size. See the error message below. Any idea why this might be happening?

![image](https://user-images.githubusercontent.com/80861276/133936761-952fec95-eed0-401d-b4d5-9a793948363f.png)

**Comment by dchoi27** [comment]
Hey there, are you using the HTTP API directly? If so, you'll run into limits with Cloudflare Workers (100MB). The JS client library will automatically chunk things up for you when you call its `store()` method. If using the API directly, you'll need to do this yourself. See if #413 helps.

**Comment by dchoi27** [comment]
Oh that's weird! Yeah any logs would be helpful, as well as any code you can share + what environments you've tried this in.

@vasco-santos mind taking a look?

**Comment by vasco-santos** [comment]
Hello @0xSzeth 

The `store()` method uses the `/store` endpoint underneath and is used to store NFTs provided as `File/Blob`. This is problematic for files larger than `100mb` thanks to our current Cloudflare Worker limits (@dchoi27 can you let me know where do we document this limits? maybe we should look into making this more clear).

@0xSzeth with the above in mind, you will need to use `storeCar` method to upload files larger than 100mb. You can see how to do this in the [inline docs](https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/src/lib.js#L290-L324) and in the examples [Node.js](https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/examples/node.js/storeCar.js) + [Browser](https://github.com/ipfs-shipyard/nft.storage/tree/main/packages/client/examples/browser/car). In short, you need to generate a CAR file from you files, which when provided to the client will be chunked in small CAR files and work around the worker limits, while also give you verifiable guarantees of the file CID.

**Comment by vasco-santos** [comment]
@dchoi27 thanks, you seem already looking into better docs https://github.com/ipfs-shipyard/nft.storage/issues/449 ❤️

**Comment by 0xSzeth** [comment]
Makes sense! Definitely wasn't clear that was the case from the docs, so I appreciate you jumping in here. Will look into using CAR for now. Thank you!!

**Comment by dchoi27** [comment]
Thanks Vasco! Hey @0xSzeth - sorry looks like I had it wrong - only the `storeCar()` method and not `store()` does the automatic chunking (though we'll add it to `store()`via #220).
