### ISSUE TITLE
Using API storeDirectory function

### ISSUE THREAD

**Issue by jrwhiteh** [ipfs-shipyard/nft.storage#446]
I'm using your API storeDirectory function. First I'm storing an array of images to a directory. Next I'm pushing an array of jsons to a directory. This works just fine when done with up to 200 of each but going any higher the pics will push but the jsons will get Error: 524 Origin Time-out. Is there some specific limit on how many i can push at a time?

I read through other issues and noticed someone said that using a second API key to do the second storeDirectory works  so i tried that and it also worked for me sporadically. But I still don't see this as final solution. my directory is <100KB so i was thinking it would push fine.

this is the error:
 Error: 524: Origin Time-out
 at Function.storeDirectory

**Comment by dchoi27** [comment]
Hey, this is likely related to #434. We're looking at it!

**Comment by alanshaw** [comment]
@jrwhiteh could you please try again to check?

**Comment by jrwhiteh** [comment]
yes, i tried with my max which was 2000 pics and 2000 jsons and both pushes worked using storeDirectory
