### ISSUE TITLE
Error while importing `import { packToBlob } from "ipfs-car/pack/blob";` in React App.

### ISSUE THREAD

**Issue by Arvindraj73** [ipfs-shipyard/nft.storage#448]
Hi,
I tried to use `ipfs-car` to create car files but I am getting `Module not found: Can't resolve 'ipfs-car/pack/blob'` error while importing `import { packToBlob } from "ipfs-car/pack/blob";` in React App.
package.json file and node_modules have `ipfs-car`, yet I am getting the error.
`package.json`
![Screenshot from 2021-09-21 19-05-30](https://user-images.githubusercontent.com/60358829/134180844-0eec5fe7-add0-4e10-bca6-b0d102f9299d.png)

**Comment by dchoi27** [comment]
@vasco-santos any thoughts?

**Comment by vasco-santos** [comment]
Hey @Arvindraj73 

What version of react scripts are you using? If I remember correctly, there was a problem where react scripts would not support the exports property in package.json because it was using an older version of webpack.

**Comment by Arvindraj73** [comment]
I'm using `"react-scripts": "4.0.3",` and `"react": "^17.0.2",`

**Comment by vasco-santos** [comment]
That version seems to be using the latest webpack. Can you try using to make sure this is an exports problem:

```
import { packToBlob } from "ipfs-car/dist/esm/pack/blob.js"
```

**Comment by Arvindraj73** [comment]
@vasco-santos It imports and works fine when I use the import statement provided by you.
