### ISSUE TITLE
Issue of UnhandledPromiseRejectionWarning: TypeError: storage.store is not a function

### ISSUE THREAD

**Issue by happyeric77** [ipfs-shipyard/nft.storage#468]
I am struggling to upload my png file onto nft.storage using npm package.
My node js version is v12.22.1, npm version is 6.14.12

And I am using the node.js example code and made a change to my file (package.json keeps the same):

```

import fs from 'fs'
import { NFTStorage, File } from 'nft.storage'

const endpoint = 'https://api.nft.storage' // the default
const token = 'myAPIkey'

async function main() {
  const storage = new NFTStorage({ endpoint, token })
  const metadata = await storage.store({
    name: 'nft.storage store test',
    description:
      'Using the nft.storage metadata API to create ERC-1155 compatible metadata.',
    image: new File([await fs.promises.readFile('aloha.png')], 'aloha.png', {
      type: 'image/jpg',
    }),
  })
  console.log('IPFS URL for the metadata:', metadata.url)
  console.log('metadata.json contents:\n', metadata.data)
  console.log(
    'metadata.json contents with IPFS gateway URLs:\n',
    metadata.embed()
  )
}
main()
```
After that, I run npm install to install all packages.
Then I run the script and it turns the following error:
```

(node:71620) UnhandledPromiseRejectionWarning: TypeError: storage.store is not a function
    at main (file:///Users/macbookpro4eric/Projects/blockchain/project0_1_nft_storage/store.js:10:34)
(node:71620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you please let me know where do I do wrong?

**Comment by happyeric77** [comment]
I checked the source code, And it actually does not have the "store" function. What it has are storeBlob and storeDirectory.
Could anybody tell me where do I get the store method?

**Comment by alanshaw** [comment]
What version of the library are you using? Make sure you're using the latest.

**Comment by happyeric77** [comment]
Hi Alanshow, thanks for the reply,
I am actually using ^0.3.9. By using this version I am able to use the import statement to import nft.storage.

I also tried to use the up-to-date version "3.2.3", but it turns out 
1) if I use require (const { NFTStorage, File , Blob} = require("nft.storage")) trying to import module, that it gets the error as below:

```
/Users/macbookpro4eric/Projects/blockchain/project30_img_test/node_modules/@web-std/fetch/dist/index.cjs:1534
                        response_?.emit("error", err);
                                  ^

SyntaxError: Unexpected token '.'
```

2) If I use import (import { NFTStorage, File , Blob} from 'nft.storage'), it gets another error as below:

```
import { NFTStorage, File , Blob} from 'nft.storage'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

To conclude, I even cannot import the package if I use the updated version.

It is very appreciated if you could let me know where did I do wrong.

Best regards.

**Comment by dchoi27** [comment]
Should be a pretty simple fix and similar solution to #458, please check that out when @vasco-santos has had a chance to take a look!

**Comment by happyeric77** [comment]
Thanks, @dchoi27 and @vasco-santos , If there could be a revision, I would be Looking forward to it.

**Comment by vasco-santos** [comment]
@happyeric77 thanks for reaching out. We do not support Node12 these days considering it it not an active release anymore https://nodejs.org/en/about/releases/ and it would mean we could not use some of the new features like [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).

The first step here is to have Node version updated to 14 or later. After that, you can use `import statement` if you are using ESM Modules, otherwise you will need to use `require`.  Let me know if I can help you out further.

**Comment by happyeric77** [comment]
Thanks @vasco-santos , I will try to update my node to > 14.
