### ISSUE TITLE
Error: Session expired

### ISSUE THREAD

**Issue by onionpeel** [ipfs-shipyard/nft.storage#48]
I am getting an error with client.storeBlob(content).  I had been using it without any problems, but now it shows an error:
lib.js:86 Uncaught (in promise) Error: Session expired

I created a new account and tried a new API key, but the problem has persisted.  I have not exceeded the 5gb of storage.  Any ideas?

**Comment by hugomrdias** [comment]
i will take a look, @onionpeel thank you for the heads up.

**Comment by alanshaw** [comment]
@onionpeel it looks like you might be using an old token that you deleted. Can you check that the token you're using is shown in the list: https://nft.storage/manage
