### ISSUE TITLE
Messaging on homepage around IPFS / Filecoin and why they're important to use for NFTs

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#481]
Those landing on NFT.Storage without any background knowledge on content addressing might be confused why it's a valuable product. Think we cover this a bit, but think it can be improved in the `About` section.

Would make the text: `nft.storage is a brand new service, built specifically for storing off-chain NFT data. Data is stored decentralized on [IPFS](https://ipfs.io/) and [Filecoin](https://filecoin.io/), and are referenced using decentralized, content addressed IPFS URIs that can be used in your smart contract without fear of the data being referenced changing. To learn more about the importance of content addressing, check out this page on [NFT School](https://nftschool.dev/concepts/content-addressing/).`

**Comment by zebateira** [comment]
@dchoi27 is that the final copy to put on that section?


Double checking this is the section that needs the update
<img width="522" alt="image" src="https://user-images.githubusercontent.com/2353186/136049523-d82ef004-774e-4c1a-90f3-fe19859cc071.png">

**Comment by dchoi27** [comment]
yes and yes!
