### ISSUE TITLE
CORS Issue while uploading through the web API's storeDirectory

### ISSUE THREAD

**Issue by melMass** [ipfs-shipyard/nft.storage#523]
Hi,

I'm trying to upload a directory using `storage.storeDirectory(directory_content)` thought a localhost web page.
But I'm facing a CORS issue.

```ruby
Access to fetch at 'https://nft.storage/api/upload' from origin 'https://localhost:3000' has been blocked by CORS policy:  
 No 'Access-Control-Allow-Origin' header is present on the requested resource.  
if an opaque response serves your needs,  
set the request's mode to 'no-cors' to fetch the resource with CORS disabled.  

POST https://nft.storage/api/upload net::ERR_FAILED 403. 
```

The node api works fine on the same file samples.

Is there a way to overcome that?

Thanks

**Comment by melMass** [comment]
This is in context:
https://github.com/melMass/hicetnunc/blob/718efe47d4d34bf9e18c733eedf9a2434645ed03/src/data/ipfs.js#L175

It handles single files just fine:
https://github.com/melMass/hicetnunc/blob/718efe47d4d34bf9e18c733eedf9a2434645ed03/src/data/ipfs.js#L93

**Comment by melMass** [comment]
Is there another channel for support?

**Comment by alanshaw** [comment]
What is the total size of the files you're trying to upload?

**Comment by melMass** [comment]
> What is the total size of the files you're trying to upload?

I tried many different samples with different sizes. From 1mb to 99mb.
The issue only comes up when using it thought the web server, using node it works.

Since then I also tried 
- making the request myself in axios (without using the nft.storage package) but I have the same CORS issue.
- using https (self-signed using mkcert)

**Comment by NoRulesJustFeels** [comment]
Even running this nft.storage example in a Chrome browser gives the same cors error: 
https://github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/examples/browser/storeDirectory.html
