### ISSUE TITLE
Question re 5GB limit

### ISSUE THREAD

**Issue by fastackl** [ipfs-shipyard/nft.storage#54]
Say I'm starting to hit the 5GB limit.

If I click "delete" in my file dashboard, will that keep me below the 5GB limit? And allow me to continue to upload files?

![image](https://user-images.githubusercontent.com/80379118/113538229-06ab3180-961e-11eb-89a4-1cd048225d72.png)

**Comment by alanshaw** [comment]
Apologies for the delay - yes that's correct. Also, the 5GB limit has been removed. Note that the data must be used for NFTs and be be linked to from blockchains.
