### ISSUE TITLE
Is there anyway to store more than 100MB content?

### ISSUE THREAD

**Issue by trnhgquan** [ipfs-shipyard/nft.storage#63]
Hello team,

I am trying to add files more than 100MB via nft.storage, but I see it limit 100MB for each request as the same with Infura. 
Is there anyway to do it or do u will wok on in in the near future?

**Comment by alanshaw** [comment]
It is coming SOON!

**Comment by alanshaw** [comment]
This issue can now be tracked here: https://github.com/ipfs-shipyard/nft.storage/issues/173
