### ISSUE TITLE
Re-enable auto publish for the client lib 

### ISSUE THREAD

**Issue by hugomrdias** [ipfs-shipyard/nft.storage#66]
In this [PR](https://github.com/ipfs-shipyard/nft.storage/pull/61) we had to disable the auto publish CI job, because workspaces dont work when the package.json version is `0.0.0` or out of sync . If another package in the monorepo depends on the client it will always fetch from npm instead of symlinking when versions dont match.

**Comment by alanshaw** [comment]
fixed in https://github.com/ipfs-shipyard/nft.storage/commit/1dbdabaa1c1b9440ad5a32800f9029d740d600bb
