### ISSUE TITLE
API Key creation failing

### ISSUE THREAD

**Issue by Manik-Jain** [ipfs-shipyard/nft.storage#87]
Upon trying to create a new API key using the createkey button, it still says "No Keys".

**Comment by Manik-Jain** [comment]
@alanshaw Could we please check this?

**Comment by alanshaw** [comment]
Are you seeing an error message in the console?

**Comment by Manik-Jain** [comment]
Yes I see the following issues.
<img width="1423" alt="Screenshot 2021-05-01 at 15 27 35" src="https://user-images.githubusercontent.com/24981979/116792959-e7bf8400-aa91-11eb-95c1-89c83d78be11.png">

**Comment by Manik-Jain** [comment]
This is something which happens when I login with my Github credential. If I, however, login with my email, it works, intermittently, fine.

**Comment by talentlessguy** [comment]
Still happens when logging in with GitHub

![image](https://user-images.githubusercontent.com/35937217/126678643-d6a253f8-9699-4fdd-9aa1-63f6539bc4af.png)

I'm using Firefox 90

**Comment by alanshaw** [comment]
@hugomrdias do you think you could have another look at this please?

**Comment by dchoi27** [comment]
@hugomrdias was this resolved or is this still being worked on?

**Comment by hugomrdias** [comment]
@talentlessguy can you provide more info about your error? i can't reproduce

**Comment by dchoi27** [comment]
Closing for now, let us know if you're still experiencing this issue!

**Comment by talentlessguy** [comment]
I'm still experiencing this

**Comment by talentlessguy** [comment]
@hugomrdias I can't login on the website, I don't even try to upload anything

it just throws me back to the main page

and console yields this

![image](https://user-images.githubusercontent.com/35937217/131722042-97d60303-dac5-43bc-b4a0-d8d9e22a6bae.png)
