### ISSUE TITLE
NFT size not being calculated

### ISSUE THREAD

**Issue by jonyg80** [ipfs-shipyard/nft.storage#88]
Size of NFTs pinned by hash after 'version 1.0.0 update' is not being calculated .

**Comment by alanshaw** [comment]
I've also seen this. I think it's not all NFTs but needs to be fixed. Will look into this asap.

**Comment by alanshaw** [comment]
@jonyg80 this should now be resolved - if you're still seeing an issue let me know and post the CID that isn't having it's size calculated.
