### ISSUE TITLE
Polka dot/Kusuma nft marketplace

### ISSUE THREAD

**Issue by blkluv** [ipfs-shipyard/nft.storage#89]
Hello we (luvnft.com) have a new polkadot/kusuma nft marketplace on AWS. How would we go about storing our files on your platform? 

Info@luvnft.com

**Comment by jnthnvctr** [comment]
Given we chatted a few weeks ago, I'll close this out - but let us know if you're stuck!

**Comment by alanshaw** [comment]
Just closing this as I know there have been conversations outside of github. Please ping us on slack or open an issue here if there's something you need help with!
